//! Emit `Cargo.toml` for the wasm-component bridge crate
//! (DuckDB target).
//!
//! The shape mirrors `aba-component/Cargo.toml` in the ducklink
//! tree (the implementation oracle for hand-written DuckDB
//! extensions): `crate-type = ["cdylib"]` for `wasm32-wasip2`, a
//! `wit-bindgen` dep, plus the helpers we need for scalar
//! marshaling (`serde` / `serde_json` for the same JSON-as-TEXT
//! list helpers the SQLite-target bridge ships).
//!
//! No `wasmtime` / `rusqlite` — pure wasm component code; the
//! ducklink runtime supplies the imports.

use shim_bridge_codegen_core::BridgePlan;

pub fn cargo_toml(plan: &BridgePlan, crate_name: &str) -> String {
    let primary = plan
        .extensions
        .first()
        .map(|e| e.name.as_str())
        .unwrap_or("shim");
    format!(
        r##"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"
description = """
Generated by sqlink-shim-codegen (--target duckdb).
Bridges the {primary} DataFission shim onto the canonical
`duckdb:extension@2.2.0` contract as a wasm component.
Imports {primary}:wasm/*; exports duckdb:extension/guest and
duckdb:extension/callback-dispatch. Scalar-first cut: scalars
are wired; aggregates / table functions / pragmas / casts return
`Duckerror::Unsupported` until follow-up steps land them.
"""
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = {{ version = "0.41", features = ["macros"] }}
wit-bindgen-rt = {{ version = "0.41", features = ["bitflags"] }}
# Step 4 scalar-first cut: serde + serde_json are present for
# parity with sqlite-emit's JSON-as-TEXT helpers (`list<f64>`
# args parsed from `'[1.0, 2.0]'` TEXT). The DuckDB-target
# dispatch arms in this cut don't currently exercise them, but
# the build needs them on the dependency manifest for the
# `serde_json::from_str::<Vec<T>>` references in the generated
# prelude to resolve.
serde = {{ version = "1", default-features = false, features = ["derive", "alloc"] }}
serde_json = {{ version = "1", default-features = false, features = ["alloc"] }}

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
"##,
        crate_name = crate_name,
        primary = primary,
    )
}
