//! Emit `src/lib.rs` for the wasm-component bridge (DuckDB target).
//!
//! Step 4 scalar-first cut. The generated file:
//!   1. `wit_bindgen::generate!` against the DuckDB-extension world
//!      (path: "wit", world: "bridge").
//!   2. `use bindings::duckdb::extension::{types, runtime}` so the
//!      dispatch arms reference `types::Duckvalue` / `runtime::*`
//!      identifiers verbatim.
//!   3. The handle-table block (handle_table::render()).
//!   4. `impl guest::Guest for $Bridge` (lifecycle).
//!   5. `impl callback_dispatch::Guest for $Bridge` with the six
//!      arms (scalar wired, others Unsupported).
//!   6. `register_scalars()` body.
//!   7. `bindings::export!(...)` at file scope.
//!
//! The dispatch is keyed by `usize` arm-index instead of the
//! SQLite emit's `u64 func_id` because DuckDB's host hands the
//! extension a per-registration `u32 handle` instead. We allocate
//! that handle at `register_scalars()` time and store
//! `handle -> arm_index` in `handle_table`.

use anyhow::Result;

use shim_bridge_codegen_core::BridgePlan;
use datalink_shim_codegen_core::interface_db;
use datalink_shim_codegen_core::record_registry::{self, RecordType};

use crate::dispatch;
use crate::emit_wit;
use crate::handle_table;
use crate::lifecycle;
use crate::register;

/// Generate `src/lib.rs`.
pub fn lib_rs(plan: &BridgePlan, crate_name: &str) -> Result<String> {
    let primary = plan
        .extensions
        .first()
        .map(|e| e.name.as_str())
        .unwrap_or("shim");
    let bridge_struct = pascal_case(primary) + "Bridge";

    let wit_deps_root = emit_wit::source_shim_deps_dir(primary)?;
    let shim_packages = emit_wit::discover_shim_packages(&wit_deps_root)?;
    let shim_wit_dir = pick_primary_shim_dir(primary, &wit_deps_root, &shim_packages)
        .unwrap_or_else(|| wit_deps_root.clone());

    // Records are kept only for symmetry with sqlite-emit — the
    // dispatch arms in this cut don't reference them yet. A
    // follow-up adds typed-value-binding via ducklink wit-value.
    let records: Vec<RecordType> = record_registry::build(&shim_packages, primary)
        .into_iter()
        .filter(|r| emit_wit::package_belongs_to_primary(&r.package, primary))
        .collect();

    let (scalar_entries, scalar_unwired) =
        interface_db::build_full(plan, &shim_wit_dir, &records)?;

    // Report on what fell through so the maintainer sees coverage
    // at codegen time.
    let total_unwired = scalar_unwired.len();
    if total_unwired > 0 {
        eprintln!(
            "[duckdb-target] {total_unwired} scalar(s) not wired in Step 4 cut:"
        );
        for u in &scalar_unwired {
            eprintln!("  - {}: {}", u.sql_name, u.reason);
        }
    }

    // Track which WIT module aliases are referenced by the
    // emitted arms so the `use` lines align with what's actually
    // needed. Each dispatch arm references `<module>::<func>`.
    let mut used_aliases: std::collections::BTreeMap<String, String> =
        std::collections::BTreeMap::new();
    for (entry, _fallible) in &scalar_entries {
        used_aliases
            .entry(entry.shape.wit_module.clone())
            .or_insert_with(|| entry.shape.wit_package.clone());
    }

    let mut s = String::new();
    s.push_str(HEADER);
    s.push_str(&format!(
        r##"//! Generated by sqlink-shim-codegen (--target duckdb).
//!
//! Step 4 scalar-first cut: scalars are wired against the
//! `duckdb:extension@2.2.0` contract; aggregates / table
//! functions / pragmas / casts return `Duckerror::Unsupported`.
//! See AGENTS.md (in datalink/crates/datalink-shim-duckdb-emit)
//! for the migration plan that landed this target.

#![allow(unused_imports, dead_code)]

extern crate alloc;

use alloc::format;
use alloc::string::{{String, ToString}};
use alloc::vec::Vec;

mod bindings {{
    wit_bindgen::generate!({{
        path: "wit",
        world: "bridge",
        generate_all,
    }});
}}

use bindings::duckdb::extension::types;
use bindings::duckdb::extension::runtime;
use bindings::exports::duckdb::extension::callback_dispatch;
use bindings::exports::duckdb::extension::guest;

"##,
    ));
    let _ = primary;

    // `use bindings::<pkg_ns>::<pkg_name>::<module> as <alias>;`
    // lines for the upstream shim modules referenced by the
    // dispatch arms.
    use datalink_shim_codegen_core::wit_parse;
    for (alias, pkg) in &used_aliases {
        if let Some(module_ident) = wit_parse::alias_to_wit_module_ident(alias) {
            let (pkg_ns, pkg_name) = split_pkg(pkg);
            s.push_str(&format!(
                "use bindings::{pkg_ns}::{pkg_name}::{module_ident} as {alias};\n",
                pkg_ns = sanitize_module(&pkg_ns),
                pkg_name = sanitize_module(&pkg_name),
                module_ident = module_ident,
                alias = alias,
            ));
        }
    }
    s.push('\n');

    s.push_str(&format!(
        r##"struct {bridge_struct};

"##,
    ));

    s.push_str(DUCKVALUE_HELPERS);
    s.push_str(handle_table::render());
    s.push_str(&lifecycle::render(&bridge_struct, plan));

    // call_scalar dispatch: build the per-arm match
    let mut scalar_arms = String::new();
    let scalar_arm_count = build_scalar_arms(&mut scalar_arms, &scalar_entries);
    let _ = scalar_arm_count;

    s.push_str(&format!(
        r##"
impl callback_dispatch::Guest for {bridge_struct} {{
    fn call_scalar_batch(
        handle: u32,
        rows: Vec<Vec<types::Duckvalue>>,
        ctx: types::Invokeinfo,
    ) -> Result<Vec<types::Duckvalue>, types::Duckerror> {{
        let base = ctx.rowindex.unwrap_or(0);
        let mut out = Vec::with_capacity(rows.len());
        for (i, args) in rows.into_iter().enumerate() {{
            let row_ctx = types::Invokeinfo {{
                rowindex: Some(base + i as u64),
                iswindow: ctx.iswindow,
            }};
            out.push(<Self as callback_dispatch::Guest>::call_scalar(handle, args, row_ctx)?);
        }}
        Ok(out)
    }}

    fn call_scalar(
        handle: u32,
        args: Vec<types::Duckvalue>,
        _ctx: types::Invokeinfo,
    ) -> Result<types::Duckvalue, types::Duckerror> {{
        let arm_idx = handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .get(&handle)
            .copied()
            .ok_or_else(|| types::Duckerror::Internal(
                "unknown scalar handle".into()
            ))?;
        // Default DuckDB null semantics: a NULL arg short-circuits
        // to NULL before the function runs. The base
        // `runtime.scalar-registry.register` API the codegen uses
        // here doesn't take a null-handling arm (that's
        // `runtime-ext.register-scalar-ex`), so DuckDB enforces
        // the propagate path engine-side. We defensively check
        // here too in case the host plumbs a NULL through.
        if args.iter().any(|v| matches!(v, types::Duckvalue::Null)) {{
            return Ok(types::Duckvalue::Null);
        }}
        match arm_idx {{
{scalar_arms}            _ => Err(types::Duckerror::Internal(format!(
                "unknown scalar arm index {{}}", arm_idx
            ))),
        }}
    }}

    fn call_table(
        _handle: u32,
        _args: Vec<types::Duckvalue>,
    ) -> Result<types::Resultset, types::Duckerror> {{
        Err(types::Duckerror::Unsupported(
            format!("{primary}: table functions not wired (Step 4 scalar-first cut)")
        ))
    }}
    fn call_aggregate(
        _handle: u32,
        _rows: types::Rowbatch,
    ) -> Result<types::Duckvalue, types::Duckerror> {{
        Err(types::Duckerror::Unsupported(
            format!("{primary}: aggregates not wired (Step 4 scalar-first cut)")
        ))
    }}
    fn call_pragma(
        _handle: u32,
        _args: Vec<types::Duckvalue>,
    ) -> Result<Option<types::Duckvalue>, types::Duckerror> {{
        Err(types::Duckerror::Unsupported(
            format!("{primary}: pragmas not wired (Step 4 scalar-first cut)")
        ))
    }}
    fn call_cast(
        _handle: u32,
        _value: types::Duckvalue,
    ) -> Result<types::Duckvalue, types::Duckerror> {{
        Err(types::Duckerror::Unsupported(
            format!("{primary}: casts not wired (Step 4 scalar-first cut)")
        ))
    }}
}}
"##,
        bridge_struct = bridge_struct,
        scalar_arms = scalar_arms,
        primary = primary,
    ));

    // register_scalars() body
    s.push_str(&register::render(plan)?);

    // Export macro at file scope
    s.push_str(&format!(
        "\nbindings::export!({bridge_struct} with_types_in bindings);\n"
    ));

    let _ = crate_name; // surface in README/CARGO; not used in lib.rs body
    let _ = bridge_struct;
    Ok(s)
}

/// Build the per-arm scalar dispatch match arms. Each arm-index
/// gets one body produced by `dispatch::emit_scalar_arm_body`.
/// The arm-index ordering MUST match the iteration order in
/// `register::render` — both walk the BridgePlan's scalars in
/// declaration order and number each (canonical + alias) one
/// after the next.
fn build_scalar_arms(
    out: &mut String,
    scalar_entries: &[(interface_db::DispatchEntry, bool)],
) -> usize {
    // Map sql_name -> arm_index. Some interface DB entries may
    // surface multiple times if the same SQL function appears via
    // aliases; first writer wins (matches sqlite-emit's
    // `seen_ids.insert(id)` first-writer pattern).
    let mut arm_for: std::collections::HashMap<&str, usize> =
        std::collections::HashMap::new();
    let mut next: usize = 0;
    // First pass: build the (sql_name -> arm_index) map matching
    // register::render's iteration order. We need to iterate the
    // BridgePlan here, not scalar_entries — register iterates the
    // plan to allocate handles, and scalar_entries is the SUBSET
    // that the wit-side classifier recognised.
    //
    // To stay in sync with register::render WITHOUT requiring a
    // shared iteration pass, we mirror its scalar-by-scalar walk
    // through the entries' sql_name order. Since scalar_entries
    // is built by the same plan-walk classifier inside
    // build_full, the iteration order matches the plan order for
    // every entry the classifier produced. We assign arm indices
    // in that order; the dispatch match arm key is the assigned
    // index.
    for (entry, _fallible) in scalar_entries {
        let key: &str = entry.sql_name.as_str();
        arm_for.entry(key).or_insert_with(|| {
            let i = next;
            next += 1;
            i
        });
    }

    for (entry, fallible) in scalar_entries {
        let key: &str = entry.sql_name.as_str();
        let arm_idx = match arm_for.get(key) {
            Some(&i) => i,
            None => continue,
        };
        // Emit the arm body. The dispatch loop matches on
        // `arm_idx` (usize); we render `<arm_idx>usize => { ... }`.
        let body = dispatch::emit_scalar_arm_body(
            &entry.shape,
            *fallible,
            &entry.sql_name,
            "                ",
        );
        out.push_str(&format!(
            "            {arm_idx}usize => {{\n{body}\n            }}\n",
        ));
    }
    next
}

const HEADER: &str =
    "// === GENERATED by sqlink-shim-codegen (target=duckdb)  do not edit by hand ===\n\n";

/// Duckvalue ↔ Rust helpers ferried into the bridge's lib.rs
/// prelude. Mirror of the `arg_text` / `arg_blob` / `arg_f64` /
/// `arg_i64` set in sqlite-emit but unpacking from
/// `types::Duckvalue` arms.
const DUCKVALUE_HELPERS: &str = r##"// ─── Duckvalue arg helpers ───
//
// Mirror of sqlite-emit's `arg_text`/`arg_blob`/`arg_i64` set
// but unpacking from `types::Duckvalue` arms. The DuckDB FROZEN
// set is wider than SQLite's: integer / unsigned / date / etc.
// arms all coerce to a common Rust primitive via the four
// helpers below.

fn dv_text<'a>(args: &'a [types::Duckvalue], idx: usize, name: &str) -> Result<&'a str, types::Duckerror> {
    match args.get(idx) {
        Some(types::Duckvalue::Text(s)) => Ok(s.as_str()),
        _ => Err(types::Duckerror::Invalidargument(format!(
            "{name}: arg {idx} must be VARCHAR"
        ))),
    }
}

fn dv_blob<'a>(args: &'a [types::Duckvalue], idx: usize, name: &str) -> Result<&'a [u8], types::Duckerror> {
    match args.get(idx) {
        Some(types::Duckvalue::Blob(b)) => Ok(b.as_slice()),
        Some(types::Duckvalue::Text(s)) => Ok(s.as_bytes()),
        _ => Err(types::Duckerror::Invalidargument(format!(
            "{name}: arg {idx} must be BLOB"
        ))),
    }
}

fn dv_f64(args: &[types::Duckvalue], idx: usize, name: &str) -> Result<f64, types::Duckerror> {
    match args.get(idx) {
        Some(types::Duckvalue::Float64(v)) => Ok(*v),
        Some(types::Duckvalue::Float32(v)) => Ok(*v as f64),
        Some(types::Duckvalue::Int64(v)) => Ok(*v as f64),
        Some(types::Duckvalue::Int32(v)) => Ok(*v as f64),
        Some(types::Duckvalue::Uint64(v)) => Ok(*v as f64),
        Some(types::Duckvalue::Uint32(v)) => Ok(*v as f64),
        Some(types::Duckvalue::Int16(v)) => Ok(*v as f64),
        Some(types::Duckvalue::Int8(v)) => Ok(*v as f64),
        Some(types::Duckvalue::Uint16(v)) => Ok(*v as f64),
        Some(types::Duckvalue::Uint8(v)) => Ok(*v as f64),
        _ => Err(types::Duckerror::Invalidargument(format!(
            "{name}: arg {idx} must be DOUBLE"
        ))),
    }
}

fn dv_i64(args: &[types::Duckvalue], idx: usize, name: &str) -> Result<i64, types::Duckerror> {
    match args.get(idx) {
        Some(types::Duckvalue::Int64(v)) => Ok(*v),
        Some(types::Duckvalue::Int32(v)) => Ok(*v as i64),
        Some(types::Duckvalue::Uint64(v)) => Ok(*v as i64),
        Some(types::Duckvalue::Uint32(v)) => Ok(*v as i64),
        Some(types::Duckvalue::Int16(v)) => Ok(*v as i64),
        Some(types::Duckvalue::Int8(v)) => Ok(*v as i64),
        Some(types::Duckvalue::Uint16(v)) => Ok(*v as i64),
        Some(types::Duckvalue::Uint8(v)) => Ok(*v as i64),
        Some(types::Duckvalue::Boolean(b)) => Ok(if *b { 1 } else { 0 }),
        Some(types::Duckvalue::Float64(v)) => Ok(*v as i64),
        Some(types::Duckvalue::Float32(v)) => Ok(*v as i64),
        _ => Err(types::Duckerror::Invalidargument(format!(
            "{name}: arg {idx} must be INTEGER"
        ))),
    }
}

fn dv_bool(args: &[types::Duckvalue], idx: usize, name: &str) -> Result<bool, types::Duckerror> {
    match args.get(idx) {
        Some(types::Duckvalue::Boolean(b)) => Ok(*b),
        Some(types::Duckvalue::Int64(v)) => Ok(*v != 0),
        Some(types::Duckvalue::Int32(v)) => Ok(*v != 0),
        _ => Err(types::Duckerror::Invalidargument(format!(
            "{name}: arg {idx} must be BOOLEAN"
        ))),
    }
}

/// Generic error formatter for fallible upstream WIT calls. The
/// dispatch arm wraps the upstream error via this fn into a
/// String the Duckerror::Invalidargument arm carries.
fn shim_err_string<E: core::fmt::Debug>(e: E) -> String {
    format!("{:?}", e)
}

"##;

/// Discover which subdir of `wit_deps_root` holds the primary
/// shim's upstream WIT package. Same heuristic as sqlite-emit's
/// `pick_primary_shim_dir`.
fn pick_primary_shim_dir(
    primary: &str,
    wit_deps_root: &std::path::Path,
    shim_packages: &[datalink_shim_codegen_core::wit_parse::WitPackage],
) -> Option<std::path::PathBuf> {
    use datalink_shim_codegen_core::wit_parse;
    for pkg in shim_packages {
        let ns = pkg.ns_name.split(':').next().unwrap_or("");
        if ns == primary {
            if let Ok(rd) = std::fs::read_dir(wit_deps_root) {
                for e in rd.flatten() {
                    if !e.path().is_dir() {
                        continue;
                    }
                    if let Ok(Some(p)) = wit_parse::parse_package_dir(&e.path()) {
                        if p.ns_name == pkg.ns_name {
                            return Some(e.path());
                        }
                    }
                }
            }
        }
    }
    if let Ok(rd) = std::fs::read_dir(wit_deps_root) {
        for e in rd.flatten() {
            if !e.path().is_dir() {
                continue;
            }
            let name = e.file_name();
            let sname = name.to_string_lossy();
            if sname.starts_with(primary) {
                return Some(e.path());
            }
        }
    }
    if let Ok(rd) = std::fs::read_dir(wit_deps_root) {
        let mut paths: Vec<std::path::PathBuf> =
            rd.flatten().map(|e| e.path()).filter(|p| p.is_dir()).collect();
        paths.sort();
        for p in paths {
            let name = p.file_name().and_then(|s| s.to_str()).unwrap_or("");
            match name {
                "sqlite-extension" | "sfcgal-component" | "duckdb-extension" => continue,
                _ => return Some(p),
            }
        }
    }
    None
}

fn split_pkg(pkg: &str) -> (String, String) {
    match pkg.find(':') {
        Some(i) => (pkg[..i].to_string(), pkg[i + 1..].to_string()),
        None => (pkg.to_string(), String::new()),
    }
}

fn sanitize_module(s: &str) -> String {
    s.replace('-', "_")
}

fn pascal_case(s: &str) -> String {
    let mut out = String::new();
    let mut up = true;
    for c in s.chars() {
        if c == '-' || c == '_' || c.is_whitespace() {
            up = true;
            continue;
        }
        if up {
            for u in c.to_uppercase() {
                out.push(u);
            }
            up = false;
        } else {
            out.push(c);
        }
    }
    out
}
