//! Emit the `README.md` for the wasm-component bridge crate
//! (DuckDB target).

use shim_bridge_codegen_core::BridgePlan;

pub fn readme(plan: &BridgePlan, crate_name: &str) -> String {
    let primary = plan
        .extensions
        .first()
        .map(|e| e.name.as_str())
        .unwrap_or("shim");
    let version = plan
        .extensions
        .first()
        .map(|e| e.version.as_str())
        .unwrap_or("0.1.0");

    let (sc, ag, tf, wf, ct, op, cw, pp, sct, idx) = match plan.extensions.first() {
        Some(e) => (
            e.scalars.len(),
            e.aggregates.len(),
            e.table_functions.len(),
            e.window_functions.len(),
            e.column_types.len(),
            e.operators.len(),
            e.cast_rewrites.len(),
            e.preprocessor_patterns.len(),
            e.system_catalog_tables.len(),
            e.spatial_indexes.len(),
        ),
        None => (0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
    };

    let crate_underscore = crate_name.replace('-', "_");

    format!(
        r##"# {crate_name}

Generated by [`sqlink-shim-codegen`](https://github.com/tegmentum/sqlink-shim-codegen)
from `{primary}-interface.sqlite` with `--target duckdb`.

**Do not edit by hand** — regenerate from the interface DB.

## Step 4 status

This bridge is a **scalar-first cut** (Step 4 of
`PLAN-shim-codegen-datalink-migration`). Scalars are wired
end-to-end against the `duckdb:extension@2.2.0` contract;
aggregates / table functions / pragmas / casts return
`Duckerror::Unsupported`. The verification gate at Step 4 is
that the crate `cargo build --target wasm32-wasip2 --release`
cleanly — full smoke-tests against a ducklink runtime are
deferred until ducklink-loader gains the wit-value lift the
SQLite-target wires via sqlink-loader (#559).

## Surface from the interface DB

| extension | version | scalars | aggregates | UDTFs | windows | types | operators | casts | preprocessors | catalog | indexes |
|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
| {primary} | {version} | {sc} | {ag} | {tf} | {wf} | {ct} | {op} | {cw} | {pp} | {sct} | {idx} |

## Build

```sh
cargo build --target wasm32-wasip2 --release
```

The build needs `wit-bindgen` and an installed `wasm32-wasip2`
target (`rustup target add wasm32-wasip2`).

## Compose with the upstream shim wasm

The DuckDB target composes the same way the SQLite target does —
`wac plug` the upstream `<primary>-composed.wasm` into this
crate's wasm, then a ducklink-loader integration step (deferred)
loads the composed artifact.

```sh
wac plug \
  --plug ~/git/{primary}-wasm/{primary}-composed.wasm \
  -o {primary}-ducklink-loadable.wasm \
  target/wasm32-wasip2/release/{crate_underscore}.wasm
```

## Regenerate

```sh
cd ~/git/sqlink-shim-codegen
cargo run --release -- \
  --target duckdb \
  --interface /path/to/{primary}-interface.sqlite \
  --out ~/git/{crate_name}
```

## License

Apache-2.0.
"##,
        crate_name = crate_name,
        primary = primary,
        version = version,
        crate_underscore = crate_underscore,
        sc = sc,
        ag = ag,
        tf = tf,
        wf = wf,
        ct = ct,
        op = op,
        cw = cw,
        pp = pp,
        sct = sct,
        idx = idx,
    )
}
