//! Neutral core for the `piglatin` extension — Pig Latin — written ONCE.
//! `to_pig_latin(text)` moves the leading consonant cluster of each word to the
//! end and adds "ay"; vowel-initial words get "way". The case of the word's
//! first letter is preserved. NULL -> NULL. The per-DB shim is generated by
//! [`declare!`](datalink_extcore::declare).

extern crate alloc;

use datalink_extcore::NeutralValue;

/// Logic, byte-for-byte the pre-pullup algorithm (DB-agnostic).
pub mod logic {
    fn is_vowel(c: char) -> bool {
        "aeiouAEIOU".contains(c)
    }

    pub fn pig_word(w: &str) -> String {
        let chars: Vec<char> = w.chars().collect();
        if chars.is_empty() || !chars[0].is_ascii_alphabetic() {
            return w.to_string();
        }
        if is_vowel(chars[0]) {
            return format!("{}way", w);
        }
        let split = chars
            .iter()
            .position(|c| is_vowel(*c) || !c.is_ascii_alphabetic())
            .unwrap_or(chars.len());
        let (lead, rest): (String, String) =
            (chars[..split].iter().collect(), chars[split..].iter().collect());
        let cap = chars[0].is_ascii_uppercase();
        let mut moved = format!("{}{}ay", rest, lead.to_lowercase());
        if cap {
            let mut c = moved.chars();
            if let Some(f) = c.next() {
                moved = format!("{}{}", f.to_ascii_uppercase(), c.as_str());
            }
        }
        moved
    }

    pub fn to_pig_latin(s: &str) -> String {
        s.split(' ').map(pig_word).collect::<Vec<_>>().join(" ")
    }
}

datalink_extcore::declare! {
    core = Core;
    extension = "piglatin";
    version = env!("CARGO_PKG_VERSION");

    scalar to_pig_latin(text) -> text [propagate, deterministic] = |args| {
        let s = args.arg_text(0, "to_pig_latin")?;
        Ok(NeutralValue::Text(logic::to_pig_latin(&s)))
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use datalink_extcore::ExtCore;

    fn idx(n: &str) -> usize {
        Core::DECLS.iter().position(|d| d.name == n).unwrap()
    }
    fn t(s: &str) -> NeutralValue {
        NeutralValue::Text(String::from(s))
    }

    #[test]
    fn matches_baseline() {
        assert_eq!(Core::dispatch(idx("to_pig_latin"), &[t("hello world")]).unwrap(), t("ellohay orldway"));
        assert_eq!(Core::dispatch(idx("to_pig_latin"), &[t("Apple")]).unwrap(), t("Appleway"));
    }
}
