//! Neutral core for the `polyline` extension — Google Encoded Polyline
//! encode/decode (via the `polyline` crate) — written ONCE.
//!
//!   * `polyline_encode(coords_json text, precision int64) -> text`
//!   * `polyline_decode(encoded text, precision int64) -> text`
//!
//! Coordinates are JSON arrays of `[lon, lat]` pairs (lon first, matching
//! geo-types `Coord{x=lon, y=lat}`). NULL / invalid -> NULL. The per-DB shim is
//! generated by [`declare!`](datalink_extcore::declare).

extern crate alloc;

use datalink_extcore::NeutralValue;

/// Logic, byte-for-byte the pre-pullup algorithm (DB-agnostic).
pub mod logic {
    use geo_types::{Coord, LineString};

    /// JSON array of [lon, lat] pairs -> LineString (Coord{x=lon, y=lat}).
    pub fn json_to_linestring(s: &str) -> Option<LineString<f64>> {
        let v: serde_json::Value = serde_json::from_str(s).ok()?;
        let arr = v.as_array()?;
        let mut coords = Vec::with_capacity(arr.len());
        for pair in arr {
            let p = pair.as_array()?;
            if p.len() != 2 {
                return None;
            }
            let lon = p[0].as_f64()?;
            let lat = p[1].as_f64()?;
            coords.push(Coord { x: lon, y: lat });
        }
        Some(LineString::new(coords))
    }

    /// LineString -> JSON array of [lon, lat] pairs, rounded to `precision`.
    pub fn linestring_to_json(ls: &LineString<f64>, precision: u32) -> Option<String> {
        let factor = 10f64.powi(precision as i32);
        let pairs: Vec<[f64; 2]> = ls
            .coords()
            .map(|c| [(c.x * factor).round() / factor, (c.y * factor).round() / factor])
            .collect();
        serde_json::to_string(&pairs).ok()
    }

    pub fn encode(coords_json: &str, precision: u32) -> Option<String> {
        let ls = json_to_linestring(coords_json)?;
        polyline::encode_coordinates(ls, precision).ok()
    }

    pub fn decode(encoded: &str, precision: u32) -> Option<String> {
        let ls = polyline::decode_polyline(encoded, precision).ok()?;
        linestring_to_json(&ls, precision)
    }
}

/// Precision arg: an Int64 in 0..=11, else the default 5.
fn precision(args: &[NeutralValue], i: usize) -> u32 {
    match args.get(i) {
        Some(NeutralValue::Int64(n)) if *n >= 0 && *n <= 11 => *n as u32,
        _ => 5,
    }
}

datalink_extcore::declare! {
    core = Core;
    extension = "polyline";
    version = env!("CARGO_PKG_VERSION");

    scalar polyline_encode(text, int64) -> text [propagate, deterministic] = |args| {
        let coords = args.arg_text(0, "polyline_encode")?;
        let p = precision(args, 1);
        Ok(match logic::encode(&coords, p) {
            Some(s) => NeutralValue::Text(s),
            None => NeutralValue::Null,
        })
    };
    scalar polyline_decode(text, int64) -> text [propagate, deterministic] = |args| {
        let enc = args.arg_text(0, "polyline_decode")?;
        let p = precision(args, 1);
        Ok(match logic::decode(&enc, p) {
            Some(s) => NeutralValue::Text(s),
            None => NeutralValue::Null,
        })
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use datalink_extcore::ExtCore;

    fn idx(n: &str) -> usize {
        Core::DECLS.iter().position(|d| d.name == n).unwrap()
    }
    fn t(s: &str) -> NeutralValue {
        NeutralValue::Text(String::from(s))
    }

    #[test]
    fn roundtrip() {
        let enc = Core::dispatch(idx("polyline_encode"), &[t("[[0.0,0.0],[1.0,1.0]]"), NeutralValue::Int64(5)]).unwrap();
        let s = match enc {
            NeutralValue::Text(s) => s,
            _ => panic!(),
        };
        assert!(matches!(
            Core::dispatch(idx("polyline_decode"), &[NeutralValue::Text(s), NeutralValue::Int64(5)]).unwrap(),
            NeutralValue::Text(_)
        ));
    }
}
