//! Neutral core for the `pinyin` extension — Chinese Hanzi -> pinyin
//! romanization (via the `pinyin` crate) — written ONCE.
//!
//!   * `to_pinyin(text)`          -> pinyin WITH tone marks, space-separated
//!   * `to_pinyin_plain(text)`    -> pinyin WITHOUT tone marks, space-separated
//!   * `to_pinyin_initials(text)` -> first letter of each syllable, space-sep
//!
//! Hanzi are romanized; any non-Hanzi character passes through unchanged.
//! NULL -> NULL. The per-DB shim is generated by
//! [`declare!`](datalink_extcore::declare).

extern crate alloc;

use datalink_extcore::NeutralValue;

/// Logic, byte-for-byte the pre-pullup algorithm (DB-agnostic).
pub mod logic {
    use pinyin::ToPinyin;

    #[derive(Clone, Copy, PartialEq)]
    pub enum Mode {
        Tone,
        Plain,
        Initials,
    }

    /// Convert `input` to a space-separated pinyin string per mode. Hanzi
    /// characters become their pinyin syllable; runs of non-Hanzi characters
    /// pass through verbatim. Syllables and passthrough runs are separated by
    /// single spaces.
    pub fn convert(input: &str, mode: Mode) -> String {
        let mut out = String::new();
        let mut pending = String::new(); // accumulated non-Hanzi run
        let mut need_sep = false; // a space is owed before the next emitted token

        let flush_pending = |out: &mut String, pending: &mut String, need_sep: &mut bool| {
            if !pending.is_empty() {
                if *need_sep {
                    out.push(' ');
                }
                out.push_str(pending);
                pending.clear();
                *need_sep = true;
            }
        };

        for (ch, py) in input.chars().zip(input.to_pinyin()) {
            match py {
                Some(p) => {
                    flush_pending(&mut out, &mut pending, &mut need_sep);
                    if need_sep {
                        out.push(' ');
                    }
                    let syl = match mode {
                        Mode::Tone => p.with_tone(),
                        Mode::Plain => p.plain(),
                        Mode::Initials => p.first_letter(),
                    };
                    out.push_str(syl);
                    need_sep = true;
                }
                None => {
                    pending.push(ch);
                }
            }
        }
        flush_pending(&mut out, &mut pending, &mut need_sep);
        out
    }
}

datalink_extcore::declare! {
    core = Core;
    extension = "pinyin";
    version = env!("CARGO_PKG_VERSION");

    scalar to_pinyin(text) -> text [propagate, deterministic] = |args| {
        let s = args.arg_text(0, "to_pinyin")?;
        Ok(NeutralValue::Text(logic::convert(&s, logic::Mode::Tone)))
    };
    scalar to_pinyin_plain(text) -> text [propagate, deterministic] = |args| {
        let s = args.arg_text(0, "to_pinyin_plain")?;
        Ok(NeutralValue::Text(logic::convert(&s, logic::Mode::Plain)))
    };
    scalar to_pinyin_initials(text) -> text [propagate, deterministic] = |args| {
        let s = args.arg_text(0, "to_pinyin_initials")?;
        Ok(NeutralValue::Text(logic::convert(&s, logic::Mode::Initials)))
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use datalink_extcore::ExtCore;

    fn idx(n: &str) -> usize {
        Core::DECLS.iter().position(|d| d.name == n).unwrap()
    }
    fn t(s: &str) -> NeutralValue {
        NeutralValue::Text(String::from(s))
    }

    #[test]
    fn romanizes() {
        assert_eq!(Core::dispatch(idx("to_pinyin_plain"), &[t("中国")]).unwrap(), t("zhong guo"));
        assert_eq!(Core::dispatch(idx("to_pinyin_initials"), &[t("中国")]).unwrap(), t("z g"));
    }
}
