//! Neutral core for the `rapidfuzz` extension — fuzzy string matching (via the
//! `rapidfuzz` crate), complementing DuckDB's native levenshtein/jaro_winkler —
//! written ONCE.
//!
//!   * `fuzz_ratio(a, b)          -> double`  fuzzywuzzy-style similarity 0..100
//!   * `damerau_levenshtein(a, b) -> bigint`  edit distance with transpositions
//!   * `indel(a, b)               -> bigint`  insert/delete-only edit distance
//!   * `osa(a, b)                 -> bigint`  optimal string alignment distance
//!
//! Two TEXT args. NULL in either -> NULL. The per-DB shim is generated by
//! [`declare!`](datalink_extcore::declare).

extern crate alloc;

use datalink_extcore::NeutralValue;

/// Logic, byte-for-byte the pre-pullup algorithm (DB-agnostic).
pub mod logic {
    pub fn ratio(a: &str, b: &str) -> f64 {
        rapidfuzz::fuzz::ratio(a.chars(), b.chars()) * 100.0
    }
    pub fn damerau(a: &str, b: &str) -> i64 {
        rapidfuzz::distance::damerau_levenshtein::distance(a.chars(), b.chars()) as i64
    }
    pub fn indel(a: &str, b: &str) -> i64 {
        rapidfuzz::distance::indel::distance(a.chars(), b.chars()) as i64
    }
    pub fn osa(a: &str, b: &str) -> i64 {
        rapidfuzz::distance::osa::distance(a.chars(), b.chars()) as i64
    }
}

datalink_extcore::declare! {
    core = Core;
    extension = "rapidfuzz";
    version = env!("CARGO_PKG_VERSION");

    scalar fuzz_ratio(text, text) -> float64 [propagate, deterministic] = |args| {
        let a = args.arg_text(0, "fuzz_ratio")?;
        let b = args.arg_text(1, "fuzz_ratio")?;
        Ok(NeutralValue::Float64(logic::ratio(&a, &b)))
    };
    scalar damerau_levenshtein(text, text) -> int64 [propagate, deterministic] = |args| {
        let a = args.arg_text(0, "damerau_levenshtein")?;
        let b = args.arg_text(1, "damerau_levenshtein")?;
        Ok(NeutralValue::Int64(logic::damerau(&a, &b)))
    };
    scalar indel(text, text) -> int64 [propagate, deterministic] = |args| {
        let a = args.arg_text(0, "indel")?;
        let b = args.arg_text(1, "indel")?;
        Ok(NeutralValue::Int64(logic::indel(&a, &b)))
    };
    scalar osa(text, text) -> int64 [propagate, deterministic] = |args| {
        let a = args.arg_text(0, "osa")?;
        let b = args.arg_text(1, "osa")?;
        Ok(NeutralValue::Int64(logic::osa(&a, &b)))
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use datalink_extcore::ExtCore;

    fn idx(n: &str) -> usize {
        Core::DECLS.iter().position(|d| d.name == n).unwrap()
    }
    fn t(s: &str) -> NeutralValue {
        NeutralValue::Text(String::from(s))
    }

    #[test]
    fn distances() {
        assert_eq!(Core::dispatch(idx("osa"), &[t("abc"), t("abc")]).unwrap(), NeutralValue::Int64(0));
        assert_eq!(Core::dispatch(idx("indel"), &[t("abc"), t("abd")]).unwrap(), NeutralValue::Int64(2));
    }
}
