//! Neutral core for the `blast` extension — BLASTN + BLASTP via rust-bio's
//! Smith-Waterman aligner + Karlin-Altschul statistics. Two table
//! functions are exposed, both taking three JSON VARCHAR args
//! (queries, subjects, options) and emitting the 13-column hit shape
//! DuckDB users see.
//!
//! The per-DB shim is generated by `datalink_extcore::duckdb_shim!` in
//! `synphage-ducklink/components/blast/`. No sqlink shim yet — SQLite
//! table-valued functions use a different `vtab` shape and would need
//! `shim_sqlite`'s Table skip flipped to a real port.
//!
//! ## Why JSON string args instead of LIST(STRUCT(...))
//!
//! DuckLink 4.0.0's binder flattens `Logicaltype::Complex(...)` down to
//! `VARCHAR[]` at the DuckDB layer — the STRUCT payload is lost. Every
//! DuckLink-loadable component in the ecosystem takes JSON string args
//! for compound types instead. Callers build the JSON with
//! `to_json(list(struct_pack(...)))` (native `json` extension) or
//! `string_agg + json_quote` (the `jsonfns` component).
//!
//! ## Pushdown-in-options
//!
//! `SearchOptions` carries five filter knobs (evalue_max, min_identity,
//! query_keys, subject_keys, strand) that would normally reach an
//! extension via DuckDB's `WHERE`-pushdown machinery. That path is
//! DEPRECATED in ducklink-extension v5.0.0 (removal at v6.0.0), so
//! callers pass filter intent explicitly here. See `pushdown.rs`.

// The declare! macro emits `alloc::vec!` / `alloc::string::String` — imported
// explicitly (works alongside std, alloc is always available).
extern crate alloc;

mod align;
mod filter;
pub mod model;
mod pushdown;
mod scoring;
mod strand;

use datalink_extcore::{ArgExt as _, NeutralValue};

use crate::model::{Hit, Scoring, SearchError, SearchOptions, Sequence, Strand};

datalink_extcore::declare! {
    core = Core;
    extension = "blast";
    version = env!("CARGO_PKG_VERSION");

    table blastn(text, text, text) -> (
        query_key: text,
        subject_key: text,
        query_start: int64,
        query_end: int64,
        subject_start: int64,
        subject_end: int64,
        strand: text,
        identity_count: int64,
        alignment_length: int64,
        percent_identity: float64,
        bit_score: float64,
        raw_score: float64,
        evalue: float64,
    ) [deterministic] = |args| {
        run_from_json(args, "blastn", Scoring::BlastnDefault)
    };

    table blastp(text, text, text) -> (
        query_key: text,
        subject_key: text,
        query_start: int64,
        query_end: int64,
        subject_start: int64,
        subject_end: int64,
        strand: text,
        identity_count: int64,
        alignment_length: int64,
        percent_identity: float64,
        bit_score: float64,
        raw_score: float64,
        evalue: float64,
    ) [deterministic] = |args| {
        run_from_json(args, "blastp", Scoring::BlastpDefault)
    };
}

// ---- shared body -------------------------------------------------------

fn run_from_json(
    args: &[NeutralValue],
    fname: &str,
    scoring: Scoring,
) -> Result<Vec<Vec<NeutralValue>>, String> {
    let queries = parse_sequence_json(args.arg_text(0, fname)?, "queries")?;
    let subjects = parse_sequence_json(args.arg_text(1, fname)?, "subjects")?;
    let options = parse_options_json(args, 2)?;

    let hits = run_search(&queries, &subjects, &scoring, &options)
        .map_err(search_error_to_msg)?;

    Ok(hits.iter().map(hit_to_row).collect())
}

fn parse_sequence_json(json: String, name: &str) -> Result<Vec<Sequence>, String> {
    #[derive(serde::Deserialize)]
    struct Raw {
        key: String,
        data: String,
    }
    let raws: Vec<Raw> = serde_json::from_str(&json)
        .map_err(|e| format!("blast: cannot parse '{name}' JSON: {e}"))?;
    Ok(raws
        .into_iter()
        .map(|r| Sequence {
            key: r.key,
            data: r.data,
        })
        .collect())
}

/// Options are optional. Empty text or JSON `null` -> defaults.
/// NULL Duckvalue is passed through as an empty string by ArgExt.
fn parse_options_json(args: &[NeutralValue], idx: usize) -> Result<SearchOptions, String> {
    let raw = args.arg_text(idx, "blast").unwrap_or_default();
    if raw.is_empty() || raw == "null" {
        return Ok(SearchOptions::default());
    }
    serde_json::from_str(&raw)
        .map_err(|e| format!("blast: cannot parse 'options' JSON: {e}"))
}

fn hit_to_row(hit: &Hit) -> Vec<NeutralValue> {
    let strand_str = match hit.strand {
        Strand::Plus => "plus",
        Strand::Minus => "minus",
    };
    vec![
        NeutralValue::Text(hit.query_key.clone()),
        NeutralValue::Text(hit.subject_key.clone()),
        NeutralValue::Int64(hit.query_start as i64),
        NeutralValue::Int64(hit.query_end as i64),
        NeutralValue::Int64(hit.subject_start as i64),
        NeutralValue::Int64(hit.subject_end as i64),
        NeutralValue::Text(strand_str.to_string()),
        NeutralValue::Int64(hit.identity_count as i64),
        NeutralValue::Int64(hit.alignment_length as i64),
        NeutralValue::Float64(hit.percent_identity),
        NeutralValue::Float64(hit.bit_score),
        NeutralValue::Float64(hit.raw_score),
        NeutralValue::Float64(hit.evalue),
    ]
}

fn search_error_to_msg(e: SearchError) -> String {
    match e {
        SearchError::EmptyQueries => "blast: queries is empty".into(),
        SearchError::EmptySubjects => "blast: subjects is empty".into(),
        SearchError::InvalidSequence(m) => format!("blast: invalid sequence: {m}"),
        SearchError::InvalidScoring(m) => format!("blast: invalid scoring: {m}"),
        SearchError::AlignmentFailed(m) => format!("blast: alignment failed: {m}"),
    }
}

// ---- the algorithm — pushdown-aware ------------------------------------

/// Both entry points fan into this: apply the pushdown plan, run
/// pairwise Smith-Waterman on the (pruned) batches, filter + rank, then
/// post-filter by strand if pinned.
pub fn run_search(
    queries: &[Sequence],
    subjects: &[Sequence],
    scoring: &Scoring,
    options: &SearchOptions,
) -> Result<Vec<Hit>, SearchError> {
    if queries.is_empty() {
        return Err(SearchError::EmptyQueries);
    }
    if subjects.is_empty() {
        return Err(SearchError::EmptySubjects);
    }

    let plan = pushdown::plan_from_options(options);
    if plan.short_circuit {
        return Ok(Vec::new());
    }

    let mut queries: Vec<Sequence> = queries.to_vec();
    let mut subjects: Vec<Sequence> = subjects.to_vec();
    if pushdown::prune_batches(&plan, &mut queries, &mut subjects) {
        return Ok(Vec::new());
    }

    let params = scoring::resolve(scoring).map_err(SearchError::InvalidScoring)?;
    let mut hits: Vec<Hit> = Vec::new();

    for q in &queries {
        let query_bytes = q.data.as_bytes();
        if query_bytes.is_empty() {
            return Err(SearchError::InvalidSequence(format!(
                "query '{}' is empty",
                q.key
            )));
        }
        for s in &subjects {
            let subject_bytes = s.data.as_bytes();
            if subject_bytes.is_empty() {
                return Err(SearchError::InvalidSequence(format!(
                    "subject '{}' is empty",
                    s.key
                )));
            }

            if let Some(hit) = align_one(
                &q.key,
                &s.key,
                query_bytes,
                subject_bytes,
                &params,
                Strand::Plus,
            ) {
                hits.push(hit);
            }

            if params.both_strands {
                let subject_rc = strand::revcomp(subject_bytes);
                if let Some(hit) = align_one(
                    &q.key,
                    &s.key,
                    query_bytes,
                    &subject_rc,
                    &params,
                    Strand::Minus,
                ) {
                    let subject_len = subject_bytes.len() as u32;
                    hits.push(strand::translate_minus_hit(hit, subject_len));
                }
            }
        }
    }

    let hits = filter::apply(hits, options);
    Ok(pushdown::keep_strand(&plan, hits))
}

/// One (query, subject, orientation) alignment. Returns None if the
/// aligner produces an empty (zero-scoring) local path — those cases
/// carry no useful bit score or coordinates.
fn align_one(
    query_key: &str,
    subject_key: &str,
    query: &[u8],
    subject: &[u8],
    params: &scoring::Params,
    strand: Strand,
) -> Option<Hit> {
    let raw = match &params.kind {
        scoring::Kind::Blastn {
            match_reward,
            mismatch_penalty,
        } => align::run_blastn(
            query,
            subject,
            *match_reward,
            *mismatch_penalty,
            params.gap_open,
            params.gap_extend,
            params.k,
            params.lambda,
        ),
        scoring::Kind::Blastp => align::run_blastp(
            query,
            subject,
            params.gap_open,
            params.gap_extend,
            params.k,
            params.lambda,
        ),
    };

    let raw = raw?;

    // 0-based half-open [start, end) → 1-based inclusive [start, end].
    // start_1 = start_0 + 1, end_1 = end_0. Matches NCBI BLAST output.
    Some(Hit {
        query_key: query_key.to_string(),
        subject_key: subject_key.to_string(),
        query_start: (raw.query_start_0 + 1) as u32,
        query_end: raw.query_end_0 as u32,
        subject_start: (raw.subject_start_0 + 1) as u32,
        subject_end: raw.subject_end_0 as u32,
        strand,
        identity_count: raw.identity_count,
        alignment_length: raw.alignment_length,
        percent_identity: if raw.alignment_length == 0 {
            0.0
        } else {
            (raw.identity_count as f64 / raw.alignment_length as f64) * 100.0
        },
        bit_score: raw.bit_score,
        raw_score: raw.raw_score as f64,
        evalue: raw.e_value,
    })
}
