//! Neutral core for the `plist` extension — Apple property-list parsing (via
//! the `plist` crate) — written ONCE.
//!
//!   * `plist_to_json(data)`   parses an XML or binary plist into JSON.
//!   * `plist_get(data, key)`  returns a top-level dict value as text, or NULL.
//!
//! Input may arrive as TEXT (XML plist) or BLOB (binary/XML plist); the crate
//! auto-detects the format. Any parse error yields NULL. The per-DB shim is
//! generated by [`declare!`](datalink_extcore::declare).

extern crate alloc;

use datalink_extcore::NeutralValue;

/// Logic, byte-for-byte the pre-pullup algorithm (DB-agnostic).
pub mod logic {
    /// Parse plist bytes (XML or binary, auto-detected) into a `plist::Value`.
    pub fn parse(data: &[u8]) -> Option<plist::Value> {
        plist::Value::from_reader(std::io::Cursor::new(data)).ok()
    }

    /// Convert a `plist::Value` into a `serde_json::Value`. Data is base64,
    /// dates are RFC3339-ish strings (the crate's `to_xml_format`).
    pub fn to_json(v: &plist::Value) -> serde_json::Value {
        use serde_json::Value as J;
        match v {
            plist::Value::Boolean(b) => J::Bool(*b),
            plist::Value::Integer(i) => {
                if let Some(n) = i.as_signed() {
                    J::Number(n.into())
                } else if let Some(n) = i.as_unsigned() {
                    J::Number(n.into())
                } else {
                    J::Null
                }
            }
            plist::Value::Real(r) => serde_json::Number::from_f64(*r)
                .map(J::Number)
                .unwrap_or(J::Null),
            plist::Value::String(s) => J::String(s.clone()),
            plist::Value::Uid(u) => J::Number(u.get().into()),
            plist::Value::Data(d) => J::String(b64_encode(d)),
            plist::Value::Date(d) => J::String(d.to_xml_format()),
            plist::Value::Array(a) => J::Array(a.iter().map(to_json).collect()),
            plist::Value::Dictionary(m) => {
                let mut obj = serde_json::Map::new();
                for (k, val) in m.iter() {
                    obj.insert(k.clone(), to_json(val));
                }
                J::Object(obj)
            }
            _ => J::Null,
        }
    }

    /// Minimal standard base64 encoder (no external dep).
    pub fn b64_encode(input: &[u8]) -> String {
        const T: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
        let mut out = String::with_capacity((input.len() + 2) / 3 * 4);
        for chunk in input.chunks(3) {
            let b = [chunk[0], *chunk.get(1).unwrap_or(&0), *chunk.get(2).unwrap_or(&0)];
            let n = ((b[0] as u32) << 16) | ((b[1] as u32) << 8) | (b[2] as u32);
            out.push(T[((n >> 18) & 63) as usize] as char);
            out.push(T[((n >> 12) & 63) as usize] as char);
            out.push(if chunk.len() > 1 { T[((n >> 6) & 63) as usize] as char } else { '=' });
            out.push(if chunk.len() > 2 { T[(n & 63) as usize] as char } else { '=' });
        }
        out
    }

    /// Render a single plist value as plain text for `plist_get`. Strings come
    /// back unquoted; containers fall back to their JSON form.
    pub fn value_to_text(v: &plist::Value) -> String {
        match v {
            plist::Value::String(s) => s.clone(),
            plist::Value::Boolean(b) => if *b { "true".into() } else { "false".into() },
            plist::Value::Integer(i) => {
                if let Some(n) = i.as_signed() {
                    n.to_string()
                } else if let Some(n) = i.as_unsigned() {
                    n.to_string()
                } else {
                    String::new()
                }
            }
            plist::Value::Real(r) => r.to_string(),
            plist::Value::Uid(u) => u.get().to_string(),
            plist::Value::Date(d) => d.to_xml_format(),
            plist::Value::Data(d) => b64_encode(d),
            other => serde_json::to_string(&to_json(other)).unwrap_or_default(),
        }
    }
}

/// Coerce a neutral arg into raw bytes, accepting TEXT or BLOB.
fn bytes(args: &[NeutralValue]) -> Option<alloc::vec::Vec<u8>> {
    match args.first() {
        Some(NeutralValue::Text(s)) => Some(s.clone().into_bytes()),
        Some(NeutralValue::Blob(b)) => Some(b.clone()),
        _ => None,
    }
}

datalink_extcore::declare! {
    core = Core;
    extension = "plist";
    version = env!("CARGO_PKG_VERSION");

    scalar plist_to_json(text) -> text [propagate, deterministic] = |args| {
        let data = match bytes(args) {
            Some(d) => d,
            None => return Ok(NeutralValue::Null),
        };
        let v = match logic::parse(&data) {
            Some(v) => v,
            None => return Ok(NeutralValue::Null),
        };
        Ok(match serde_json::to_string(&logic::to_json(&v)) {
            Ok(s) => NeutralValue::Text(s),
            Err(_) => NeutralValue::Null,
        })
    };
    scalar plist_get(text, text) -> text [propagate, deterministic] = |args| {
        let data = match bytes(args) {
            Some(d) => d,
            None => return Ok(NeutralValue::Null),
        };
        let v = match logic::parse(&data) {
            Some(v) => v,
            None => return Ok(NeutralValue::Null),
        };
        let key = args.arg_text(1, "plist_get")?;
        Ok(match v.as_dictionary().and_then(|d| d.get(&key)) {
            Some(val) => NeutralValue::Text(logic::value_to_text(val)),
            None => NeutralValue::Null,
        })
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use datalink_extcore::ExtCore;

    fn idx(n: &str) -> usize {
        Core::DECLS.iter().position(|d| d.name == n).unwrap()
    }
    fn t(s: &str) -> NeutralValue {
        NeutralValue::Text(String::from(s))
    }

    const XML: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict><key>name</key><string>Ada</string></dict></plist>"#;

    #[test]
    fn parses_and_gets() {
        assert_eq!(Core::dispatch(idx("plist_get"), &[t(XML), t("name")]).unwrap(), t("Ada"));
        assert!(matches!(
            Core::dispatch(idx("plist_to_json"), &[t(XML)]).unwrap(),
            NeutralValue::Text(_)
        ));
        assert_eq!(Core::dispatch(idx("plist_get"), &[t(XML), t("absent")]).unwrap(), NeutralValue::Null);
    }
}
