//! Neutral core for the `quotedprintable` extension — MIME quoted-printable
//! (via the `quoted_printable` crate) — written ONCE. `qp_encode(text) -> text`,
//! `qp_decode(text) -> text` (robust). NULL / non-UTF-8 decode -> NULL. The
//! per-DB shim is generated by [`declare!`](datalink_extcore::declare).

extern crate alloc;

use datalink_extcore::NeutralValue;

/// Logic, byte-for-byte the pre-pullup algorithm (DB-agnostic).
pub mod logic {
    use quoted_printable::ParseMode;

    pub fn encode(s: &str) -> String {
        quoted_printable::encode_to_str(s.as_bytes())
    }

    /// Decode; `None` on a parse error or non-UTF-8 result (-> SQL NULL).
    pub fn decode(s: &str) -> Option<String> {
        quoted_printable::decode(s.as_bytes(), ParseMode::Robust)
            .ok()
            .and_then(|b| String::from_utf8(b).ok())
    }
}

datalink_extcore::declare! {
    core = Core;
    extension = "quotedprintable";
    version = env!("CARGO_PKG_VERSION");

    scalar qp_encode(text) -> text [propagate, deterministic] = |args| {
        let s = args.arg_text(0, "qp_encode")?;
        Ok(NeutralValue::Text(logic::encode(&s)))
    };
    scalar qp_decode(text) -> text [propagate, deterministic] = |args| {
        let s = args.arg_text(0, "qp_decode")?;
        Ok(match logic::decode(&s) {
            Some(t) => NeutralValue::Text(t),
            None => NeutralValue::Null,
        })
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use datalink_extcore::ExtCore;

    fn idx(n: &str) -> usize {
        Core::DECLS.iter().position(|d| d.name == n).unwrap()
    }
    fn t(s: &str) -> NeutralValue {
        NeutralValue::Text(String::from(s))
    }

    #[test]
    fn roundtrip() {
        let enc = Core::dispatch(idx("qp_encode"), &[t("héllo")]).unwrap();
        let s = match &enc {
            NeutralValue::Text(s) => s.clone(),
            _ => panic!(),
        };
        assert_eq!(Core::dispatch(idx("qp_decode"), &[NeutralValue::Text(s)]).unwrap(), t("héllo"));
    }
}
