//! Neutral core for the `prql` PARSER extension — a transparent PRQL ->
//! SQL transpiler (wraps `prqlc`) — written ONCE and consumed by BOTH the
//! ducklink (`duckdb:extension`) and sqlink (`sqlite:extension`) shims.
//! Mirrors the ggsql/dplyr-core split.
//!
//! # The transparent upgrade
//!
//! The existing catalog ships an explicit `prql_to_sql(prql) -> text`
//! scalar. THIS core makes PRQL transparent: a bare
//! `from x | filter ... | select ...` statement the built-in SQL parser
//! rejects is offered to [`parse::parse_prql`], recognized as PRQL, and
//! rewritten to ordinary SQL the host re-plans — no explicit scalar call.
//!
//! # Two consumers, one engine
//!
//!   * **ducklink** maps the neutral [`Outcome`](parse::Outcome) onto the
//!     `parser-dispatch.call-parse` surface (thin hand-written adapter).
//!   * **sqlink** declares the reserved scalar [`PARSE_FN`] (below) that
//!     the host-shell parse-failure intercept calls; the sqlink shim is
//!     GENERATED by `datalink_extcore::sqlite_shim!` — no bespoke glue.
//!
//! # std, not no_std
//!
//! Unlike ggsql/dplyr-core, this core is `std` because `prqlc` needs it.
//! The `declare!` + `sqlite_shim!` codegen path is otherwise identical
//! (`extern crate alloc;` makes the `::alloc::` paths the macros emit
//! resolve in a `std` crate).

extern crate alloc;

use datalink_extcore::NeutralValue;

pub mod parse;

pub use parse::{compile, parse_prql, Dialect, Outcome, DUCKDB, SQLITE};

/// The reserved scalar name the sqlink host-shell parse-failure intercept
/// looks for (shared parser-extension convention; see ggsql-core).
pub const PARSE_FN: &str = "__sqlink_parse";

datalink_extcore::declare! {
    core = Core;
    extension = "prql";
    version = env!("CARGO_PKG_VERSION");

    // The sqlink parser entrypoint. Generated into a `sqlite:extension`
    // scalar by `sqlite_shim!`. The host-shell intercept calls this on a
    // built-in parse failure; the body compiles PRQL to the SQLite
    // dialect. NULL return == declined; an Err == a clean parse error.
    scalar __sqlink_parse(text) -> text [propagate, deterministic] = |args| {
        let q = args.arg_text(0, PARSE_FN)?;
        match parse::parse_prql(&q, parse::SQLITE) {
            parse::Outcome::Declined => Ok(NeutralValue::Null),
            parse::Outcome::Invalid(msg) => Err(msg),
            parse::Outcome::Rewrite(sql) => Ok(NeutralValue::Text(sql)),
        }
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::string::String;
    use datalink_extcore::ExtCore;

    fn t(s: &str) -> NeutralValue {
        NeutralValue::Text(String::from(s))
    }
    fn idx(n: &str) -> usize {
        Core::DECLS.iter().position(|d| d.name == n).unwrap()
    }

    #[test]
    fn parse_fn_is_declared() {
        assert_eq!(Core::DECLS.len(), 1);
        assert_eq!(Core::DECLS[0].name, PARSE_FN);
    }

    #[test]
    fn scalar_declined_is_null() {
        let r = Core::dispatch(idx(PARSE_FN), &[t("SELECT 1")]).unwrap();
        assert_eq!(r, NeutralValue::Null);
    }

    #[test]
    fn scalar_rewrite_carries_sql() {
        let r = Core::dispatch(
            idx(PARSE_FN),
            &[t("from t | filter x > 1 | select {x}")],
        )
        .unwrap();
        match r {
            NeutralValue::Text(sql) => assert!(sql.to_uppercase().contains("SELECT")),
            other => panic!("expected rewrite text, got {other:?}"),
        }
    }
}
