//! Emit `Cargo.toml` for the wasm-component bridge crate.
//!
//! The shape mirrors `extensions/postgis-bridge/Cargo.toml` in
//! the sqlink tree (the implementation oracle):
//! `crate-type = ["cdylib"]` for `wasm32-wasip2`, a wit-bindgen
//! dep with the `macros` feature, and a small set of helpers
//! (serde_json for raster JSON marshaling and the like). No
//! wasmtime, no rusqlite, no df-plugin-loader  this is pure
//! wasm-component code; composition supplies its imports.

use shim_bridge_codegen_core::BridgePlan;

pub fn cargo_toml(plan: &BridgePlan, crate_name: &str) -> String {
    let primary = plan
        .extensions
        .first()
        .map(|e| e.name.as_str())
        .unwrap_or("shim");
    format!(
        r##"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"
description = """
Generated by sqlink-shim-codegen (Phase 1 stub, target=wasm-component).
Bridges the {primary} DataFission shim onto the canonical
`sqlite:extension/minimal`-shape contract as a wasm component.
Imports {primary}:wasm/*; exports sqlite:extension/metadata,
scalar-function, aggregate-function, vtab. Function bodies are
stubs that return their declared error variant  Phase 2
replaces them with real marshaling logic per
docs/plans/PLAN-codegen-retarget.md.
"""
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = {{ version = "0.44", features = ["macros"] }}
wit-bindgen-rt = {{ version = "0.44.0", features = ["bitflags"] }}
# Phase E: wit-value codec deps. `serde` derives Serialize +
# Deserialize on every wit-bindgen-generated type (via
# `additional_derives: [serde::Serialize, serde::Deserialize]`
# in the bindgen invocation). `ciborium` ferries the records
# through the `canon:cbor` profile. Both with `default-features =
# false` so they compile clean to wasm32-wasip2.
serde = {{ version = "1", default-features = false, features = ["derive", "alloc"] }}
ciborium = {{ version = "0.2", default-features = false }}
ciborium-io = {{ version = "0.2", default-features = false }}
# W2 (#542): JSON-as-TEXT marshaling for primitive `list<X>`
# params. The codegen-emitted `parse_json_list_<T>` helpers
# call `serde_json::from_str::<Vec<T>>` on the SQL caller's
# TEXT arg (e.g. `tfloat_at_values(seq, '[1.0, 2.0, 3.0]')`).
serde_json = {{ version = "1", default-features = false, features = ["alloc"] }}

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
"##,
        crate_name = crate_name,
        primary = primary,
    )
}
