//! Emit the `README.md` for the wasm-component bridge crate.

use shim_bridge_codegen_core::BridgePlan;

pub fn readme(plan: &BridgePlan, crate_name: &str, has_compose_wac: bool) -> String {
    let primary = plan
        .extensions
        .first()
        .map(|e| e.name.as_str())
        .unwrap_or("shim");
    let version = plan
        .extensions
        .first()
        .map(|e| e.version.as_str())
        .unwrap_or("0.1.0");

    let (sc, ag, tf, wf, ct, op, cw, pp, sct, idx) = match plan.extensions.first() {
        Some(e) => (
            e.scalars.len(),
            e.aggregates.len(),
            e.table_functions.len(),
            e.window_functions.len(),
            e.column_types.len(),
            e.operators.len(),
            e.cast_rewrites.len(),
            e.preprocessor_patterns.len(),
            e.system_catalog_tables.len(),
            e.spatial_indexes.len(),
        ),
        None => (0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
    };

    // Pick the compose recipe — `wac compose` when a compose.wac
    // was auto-emitted (stub-plug present), `wac plug` otherwise.
    // The compose.wac script encodes per-bridge plug → plug wiring
    // that `wac plug` can't synthesise; without a stub-plug, plain
    // `wac plug` against the pre-composed upstream is sufficient.
    let compose_section = if has_compose_wac {
        format!(
            r##"```sh
# Build the bridge crate + stub-plug.
cargo build --target wasm32-wasip2 --release
cargo build --target wasm32-wasip2 --release --manifest-path stub-plug/Cargo.toml

# Compose.  Pass each `let <alias> = new <pkg> {{ ... }};` package
# from compose.wac via `-d <pkg>=<path-to-wasm>`.
wac compose compose.wac \
  -d 'mobilitydb:temporal=/path/to/mdb-temporal-wasm.wasm' \
  -d 'sqlink-bridge:{primary}-w4a-stub=stub-plug/target/wasm32-wasip2/release/{crate_underscore}_w4a_stub.wasm' \
  -d 'sqlink-bridge:{primary}=target/wasm32-wasip2/release/{crate_underscore}.wasm' \
  -o {primary}-sqlink-loadable.wasm
```
"##,
            primary = primary,
            crate_underscore = crate_name.replace('-', "_"),
        )
    } else {
        format!(
            r##"```sh
wac plug \
  --plug ~/git/postgis-wasm/postgis-composed.wasm \
  -o {primary}-sqlink-loadable.wasm \
  target/wasm32-wasip2/release/{crate_underscore}.wasm
```"##,
            primary = primary,
            crate_underscore = crate_name.replace('-', "_"),
        )
    };

    format!(
        r##"# {crate_name}

Generated by [`sqlink-shim-codegen`](https://github.com/zacharywhitley/sqlink-shim-codegen)
from `{primary}-interface.sqlite` with `--target wasm-component`.

**Do not edit by hand**  regenerate from the interface DB.

## Phase 1 status (per `PLAN-codegen-retarget.md`)

This crate is a **Phase 1 STUB**. The shape compiles + composes
+ loads; every exported function body returns a marker error
(`{crate_name}: ... is stubbed in Phase 1`). Phase 2 replaces
the stubs with real marshaling logic.

## Surface from the interface DB

| extension | version | scalars | aggregates | UDTFs | windows | types | operators | casts | preprocessors | catalog | indexes |
|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
| {primary} | {version} | {sc} | {ag} | {tf} | {wf} | {ct} | {op} | {cw} | {pp} | {sct} | {idx} |

## Build (Phase 1)

```sh
cargo build --target wasm32-wasip2 --release
```

The build needs `wit-bindgen` and an installed `wasm32-wasip2`
target (`rustup target add wasm32-wasip2`).

## Compose with the upstream shim wasm

{compose_section}

The resulting `{primary}-sqlink-loadable.wasm` is what
sqlink-host's `load_extension*` path consumes.

## Verify (Phase 1)

```sh
wasm-tools validate {primary}-sqlink-loadable.wasm
```

Then load via sqlink-host and call any function  expect the
stub error variant.

## Regenerate

```sh
cd ~/git/sqlink-shim-codegen
cargo run --release -- \
  --target wasm-component \
  --interface /path/to/{primary}-interface.sqlite \
  --out ~/git/{crate_name}
```

## License

Apache-2.0.
"##,
        crate_name = crate_name,
        primary = primary,
        version = version,
        compose_section = compose_section,
        sc = sc,
        ag = ag,
        tf = tf,
        wf = wf,
        ct = ct,
        op = op,
        cw = cw,
        pp = pp,
        sct = sct,
        idx = idx,
    )
}
