//! Neutral core for the `pluscode` extension — Open Location Code (plus codes)
//! via the `open-location-code` crate — written ONCE.
//!
//!   * `pluscode_encode(lat float64, lon float64, length int64) -> text`
//!   * `pluscode_valid(code text) -> boolean`
//!   * `pluscode_decode_lat(code text) -> float64` (area center)
//!   * `pluscode_decode_lon(code text) -> float64`
//!
//! Invalid -> NULL/false. The per-DB shim is generated by
//! [`declare!`](datalink_extcore::declare).

extern crate alloc;

use datalink_extcore::NeutralValue;
use geo::Point;

datalink_extcore::declare! {
    core = Core;
    extension = "pluscode";
    version = env!("CARGO_PKG_VERSION");

    scalar pluscode_encode(float64, float64, int64) -> text [propagate, deterministic] = |args| {
        let lat = args.arg_float(0, "pluscode_encode")?;
        let lon = args.arg_float(1, "pluscode_encode")?;
        // Match the pre-pullup default: a length outside 2..=15 falls back to 10.
        let len = match args.get(2) {
            Some(NeutralValue::Int64(n)) if *n >= 2 && *n <= 15 => *n as usize,
            _ => 10,
        };
        Ok(NeutralValue::Text(open_location_code::encode(Point::new(lon, lat), len)))
    };
    scalar pluscode_valid(text) -> boolean [propagate, deterministic] = |args| {
        let code = args.arg_text(0, "pluscode_valid")?;
        Ok(NeutralValue::Boolean(open_location_code::is_valid(code.trim())))
    };
    scalar pluscode_decode_lat(text) -> float64 [propagate, deterministic] = |args| {
        let code = args.arg_text(0, "pluscode_decode_lat")?;
        Ok(match open_location_code::decode(code.trim()) {
            Ok(area) => NeutralValue::Float64(area.center.lat()),
            Err(_) => NeutralValue::Null,
        })
    };
    scalar pluscode_decode_lon(text) -> float64 [propagate, deterministic] = |args| {
        let code = args.arg_text(0, "pluscode_decode_lon")?;
        Ok(match open_location_code::decode(code.trim()) {
            Ok(area) => NeutralValue::Float64(area.center.lng()),
            Err(_) => NeutralValue::Null,
        })
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use datalink_extcore::ExtCore;

    fn idx(n: &str) -> usize {
        Core::DECLS.iter().position(|d| d.name == n).unwrap()
    }

    #[test]
    fn encode_valid_decode() {
        let code = Core::dispatch(
            idx("pluscode_encode"),
            &[NeutralValue::Float64(47.0), NeutralValue::Float64(8.0), NeutralValue::Int64(10)],
        )
        .unwrap();
        let s = match code {
            NeutralValue::Text(s) => s,
            _ => panic!(),
        };
        assert_eq!(
            Core::dispatch(idx("pluscode_valid"), &[NeutralValue::Text(s)]).unwrap(),
            NeutralValue::Boolean(true)
        );
    }
}
