//! Neutral core for the `pwstrength` extension — password-strength scoring
//! (via the `passwords` crate) — written ONCE. `password_score(pw) -> double`
//! (0-100), `password_strength(pw) -> text` (very weak / weak / fair / strong /
//! very strong). NULL -> NULL. The per-DB shim is generated by
//! [`declare!`](datalink_extcore::declare).

extern crate alloc;

use datalink_extcore::NeutralValue;

/// Logic, byte-for-byte the pre-pullup algorithm (DB-agnostic).
pub mod logic {
    use passwords::{analyzer, scorer};

    pub fn score(pw: &str) -> f64 {
        scorer::score(&analyzer::analyze(pw))
    }

    pub fn label(score: f64) -> &'static str {
        if score < 20.0 {
            "very weak"
        } else if score < 40.0 {
            "weak"
        } else if score < 60.0 {
            "fair"
        } else if score < 80.0 {
            "strong"
        } else {
            "very strong"
        }
    }
}

datalink_extcore::declare! {
    core = Core;
    extension = "pwstrength";
    version = env!("CARGO_PKG_VERSION");

    scalar password_score(text) -> float64 [propagate, deterministic] = |args| {
        let pw = args.arg_text(0, "password_score")?;
        Ok(NeutralValue::Float64(logic::score(&pw)))
    };
    scalar password_strength(text) -> text [propagate, deterministic] = |args| {
        let pw = args.arg_text(0, "password_strength")?;
        Ok(NeutralValue::Text(String::from(logic::label(logic::score(&pw)))))
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use datalink_extcore::ExtCore;

    fn idx(n: &str) -> usize {
        Core::DECLS.iter().position(|d| d.name == n).unwrap()
    }

    #[test]
    fn scores_and_labels() {
        let s = Core::dispatch(idx("password_score"), &[NeutralValue::Text(String::from("a"))]).unwrap();
        assert!(matches!(s, NeutralValue::Float64(_)));
        let l = Core::dispatch(idx("password_strength"), &[NeutralValue::Text(String::from("a"))]).unwrap();
        assert!(matches!(l, NeutralValue::Text(_)));
    }
}
