//! Neutral core for the `pluralize` extension — English inflection (via the
//! `pluralizer` crate) — written ONCE. `pluralize(word) -> text`,
//! `singularize(word) -> text`. NULL -> NULL. The per-DB shim is generated by
//! [`declare!`](datalink_extcore::declare).

extern crate alloc;

use datalink_extcore::NeutralValue;

/// Logic, byte-for-byte the pre-pullup algorithm (DB-agnostic). `count == 2`
/// pluralizes, `count == 1` singularizes (the `pluralizer` crate convention).
pub mod logic {
    pub fn inflect(word: &str, plural: bool) -> String {
        pluralizer::pluralize(word, if plural { 2 } else { 1 }, false)
    }
}

datalink_extcore::declare! {
    core = Core;
    extension = "pluralize";
    version = env!("CARGO_PKG_VERSION");

    scalar pluralize(text) -> text [propagate, deterministic] = |args| {
        let s = args.arg_text(0, "pluralize")?;
        Ok(NeutralValue::Text(logic::inflect(&s, true)))
    };
    scalar singularize(text) -> text [propagate, deterministic] = |args| {
        let s = args.arg_text(0, "singularize")?;
        Ok(NeutralValue::Text(logic::inflect(&s, false)))
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use datalink_extcore::ExtCore;

    fn idx(n: &str) -> usize {
        Core::DECLS.iter().position(|d| d.name == n).unwrap()
    }
    fn t(s: &str) -> NeutralValue {
        NeutralValue::Text(String::from(s))
    }

    #[test]
    fn inflects() {
        assert_eq!(Core::dispatch(idx("pluralize"), &[t("cat")]).unwrap(), t("cats"));
        assert_eq!(Core::dispatch(idx("singularize"), &[t("cats")]).unwrap(), t("cat"));
    }
}
