//! Emit `src/lib.rs` for the wasm-component bridge (datafission
//! target).
//!
//! Scalar-first cut. The generated file:
//!   1. `wit_bindgen::generate!` against the datafission-extension
//!      world (path: "wit", world: "bridge", generate_all).
//!   2. `use` declarations binding each upstream-shim module that
//!      the scalar dispatch arms reference, plus the datafission
//!      function-plugin type aliases (`types::ScalarValue` /
//!      `types::FunctionError` / `types::LogicalType`).
//!   3. `struct Component;` — the single Guest implementer for
//!      every export interface of the composite world.
//!   4. `impl identity::Guest for Component` — returns the primary
//!      name + version.
//!   5. `impl sql_extension_plugin::metadata::Guest for Component`
//!      — empty cast / operator / preprocessor lists.
//!   6. `impl scalar_function_registry::Guest for Component` —
//!      WIRED. `list_functions()` returns the per-scalar metadata
//!      collected from the interface DB; `return_type` dispatches
//!      by name; `execute` runs the per-scalar arm body via the
//!      shape emit; `execute_batch` loops.
//!   7. Stub impls for aggregate / window / table-function
//!      registries — empty `list_functions`, per-call methods
//!      return `UnknownFunction`.
//!   8. Stub impl for multi-custom-type — empty advertisements +
//!      `Internal` errors. (The single-type `custom-type`
//!      interface is intentionally NOT exported.)
//!   9. Stub impls for spatial-index / system-catalog / index-plugin
//!      — empty advertisements + `Internal` / `UnsupportedOperation`
//!      errors.
//!  10. `export!(Component);` at file scope.
//!
//! Unlike the SQLite and DuckDB targets, datafission's contract
//! has NO `register_*` call: the host snapshots each registry's
//! `list-functions()` ONCE at `CREATE EXTENSION` time, then
//! dispatches per-call by `name` parameter. No handle table is
//! needed for the scalar path. (Aggregate accumulators DO use
//! u64 handles, but the scalar-first cut doesn't exercise them.)

use anyhow::Result;

use shim_bridge_codegen_core::BridgePlan;
use datalink_shim_codegen_core::interface_db;
use datalink_shim_codegen_core::record_registry::{self, RecordType};

use crate::dispatch;
use crate::emit_wit;

/// Generate `src/lib.rs`.
pub fn lib_rs(plan: &BridgePlan, crate_name: &str) -> Result<String> {
    let primary = plan
        .extensions
        .first()
        .map(|e| e.name.as_str())
        .unwrap_or("shim");
    let version = plan
        .extensions
        .first()
        .map(|e| e.version.as_str())
        .unwrap_or("0.1.0");

    let wit_deps_root = emit_wit::source_shim_deps_dir(primary)?;
    let shim_packages = emit_wit::discover_shim_packages(&wit_deps_root)?;
    let shim_wit_dir = pick_primary_shim_dir(primary, &wit_deps_root, &shim_packages)
        .unwrap_or_else(|| wit_deps_root.clone());

    // Pull the `datafission:extension` package version from the
    // vendored WIT so identity::api_version() reports whatever
    // contract the bridge was generated against (no hardcoded
    // "1.0.0" — a future bump flows through automatically).
    let extension_pkg = emit_wit::discover_datafission_extension_package(primary)?;
    let api_version = extension_pkg.version.clone();

    // Records are kept only for symmetry with sqlite-emit /
    // duckdb-emit — the dispatch arms in this cut don't reference
    // them yet. A follow-up adds typed-value-binding via the
    // datafission type-plugin/multi-custom-type interface.
    let records: Vec<RecordType> = record_registry::build(&shim_packages, primary)
        .into_iter()
        .filter(|r| emit_wit::package_belongs_to_primary(&r.package, primary))
        .collect();

    let (scalar_entries, scalar_unwired) =
        interface_db::build_full(plan, &shim_wit_dir, &records)?;

    // Report on what fell through so the maintainer sees coverage
    // at codegen time.
    let total_unwired = scalar_unwired.len();
    if total_unwired > 0 {
        eprintln!(
            "[datafission-target] {total_unwired} scalar(s) not wired in scalar-first cut:"
        );
        for u in &scalar_unwired {
            eprintln!("  - {}: {}", u.sql_name, u.reason);
        }
    }

    // Track which WIT module aliases are referenced by the
    // emitted arms so the `use` lines align with what's actually
    // needed. Each dispatch arm references `<module>::<func>`.
    let mut used_aliases: std::collections::BTreeMap<String, String> =
        std::collections::BTreeMap::new();
    for (entry, _fallible) in &scalar_entries {
        used_aliases
            .entry(entry.shape.wit_module.clone())
            .or_insert_with(|| entry.shape.wit_package.clone());
    }

    let mut s = String::new();
    s.push_str(HEADER);
    s.push_str(&format!(
        r##"//! Generated by sqlink-shim-codegen (--target datafission).
//!
//! Scalar-first cut: scalars are wired against the canonical
//! datafission per-capability contract (version pins
//! auto-detected from the vendored WIT at codegen time);
//! aggregates, window functions, table functions,
//! multi-custom-type, spatial indexes, system catalog, and 1D
//! index plugin export stubs that advertise nothing and return
//! `Unknown*` / `Internal` errors on per-call paths. The
//! single-type `type-plugin/custom-type` interface is
//! intentionally NOT exported — components register types
//! through `multi-custom-type` instead. See AGENTS.md (in
//! datalink/crates/datalink-shim-datafission-emit) for the
//! migration plan that landed this target.

#![allow(unused_imports, dead_code)]
// wit-bindgen 0.41's generated bindings call unsafe fns outside
// explicit unsafe blocks — fine pre-2024 but warned in edition 2024.
// Datafission's hand-written postgis extension takes the same
// posture; mute it here so the generated bridge stays warning-free.
#![allow(unsafe_op_in_unsafe_fn)]

extern crate alloc;

use alloc::format;
use alloc::string::{{String, ToString}};
use alloc::vec::Vec;

mod bindings {{
    wit_bindgen::generate!({{
        path: "wit",
        world: "bridge",
        generate_all,
    }});
}}

// Datafission's composite world routes every per-registry type
// through `datafission:function-plugin/types` (ScalarValue /
// LogicalType / FunctionError). The other plugin packages each
// declare their own `types` interface; the scalar-first cut
// names them explicitly when stubbing the corresponding Guest
// impl.
use bindings::datafission::function_plugin::types as ftypes;
use bindings::datafission::sql_extension_plugin::types as setypes;
use bindings::datafission::type_plugin::types as ttypes;
use bindings::datafission::spatial_index_plugin::types as sitypes;
use bindings::datafission::system_catalog_plugin::types as sctypes;
use bindings::datafission::index_plugin::types as ixtypes;

use bindings::exports::datafission::extension::identity;
use bindings::exports::datafission::sql_extension_plugin::metadata;
use bindings::exports::datafission::function_plugin::scalar_function_registry;
use bindings::exports::datafission::function_plugin::aggregate_function_registry;
use bindings::exports::datafission::function_plugin::window_function_registry;
use bindings::exports::datafission::function_plugin::table_function_registry;
use bindings::exports::datafission::type_plugin::multi_custom_type;
use bindings::exports::datafission::spatial_index_plugin::spatial_index;
use bindings::exports::datafission::system_catalog_plugin::system_catalog;
use bindings::exports::datafission::index_plugin::index;

// The dispatch arms render `types::FunctionError::ExecutionError`
// against the function-plugin types alias. Local `types` re-exports
// the function-plugin set so the per-arm bodies stay short.
use bindings::datafission::function_plugin::types as types;

"##,
    ));
    let _ = primary;

    // `use bindings::<pkg_ns>::<pkg_name>::<module> as <alias>;`
    // lines for the upstream shim modules referenced by the
    // dispatch arms.
    use datalink_shim_codegen_core::wit_parse;
    for (alias, pkg) in &used_aliases {
        if let Some(module_ident) = wit_parse::alias_to_wit_module_ident(alias) {
            let (pkg_ns, pkg_name) = split_pkg(pkg);
            s.push_str(&format!(
                "use bindings::{pkg_ns}::{pkg_name}::{module_ident} as {alias};\n",
                pkg_ns = sanitize_module(&pkg_ns),
                pkg_name = sanitize_module(&pkg_name),
                module_ident = module_ident,
                alias = alias,
            ));
        }
    }
    s.push('\n');

    s.push_str(SCALARVALUE_HELPERS);

    s.push_str("struct Component;\n\n");

    // ---- identity ----
    s.push_str(&format!(
        r##"impl identity::Guest for Component {{
    fn name() -> String {{ "{primary}".into() }}
    fn version() -> String {{ "{version}".into() }}
    fn api_version() -> String {{ "{api_version}".into() }}
}}

"##,
        primary = primary,
        version = version,
        api_version = api_version,
    ));

    // ---- sql-extension-plugin/metadata: empty lists ----
    s.push_str(&format!(
        r##"impl metadata::Guest for Component {{
    fn name() -> String {{ "{primary}".into() }}
    fn version() -> String {{ "{version}".into() }}

    fn list_cast_rewrites() -> Result<Vec<setypes::CastRewrite>, setypes::SqlExtError> {{
        Ok(Vec::new())
    }}
    fn list_operator_rewrites() -> Result<Vec<setypes::OperatorRewrite>, setypes::SqlExtError> {{
        Ok(Vec::new())
    }}
    fn list_preprocessor_patterns() -> Result<Vec<setypes::PreprocessorPattern>, setypes::SqlExtError> {{
        Ok(Vec::new())
    }}
}}

"##,
        primary = primary,
        version = version,
    ));

    // ---- scalar-function-registry: WIRED ----
    // Build the per-name dispatch + metadata data.
    let scalar_block = build_scalar_registry_impl(&scalar_entries, plan);
    s.push_str(&scalar_block);

    // ---- aggregate-function-registry: stub ----
    s.push_str(AGGREGATE_STUB);

    // ---- window-function-registry: stub ----
    s.push_str(WINDOW_STUB);

    // ---- table-function-registry: stub ----
    s.push_str(TABLE_STUB);

    // ---- multi-custom-type: stub ----
    // Note: the single-type `type-plugin/custom-type` interface is
    // intentionally NOT exported by the generated world (see
    // `emit_wit::render_world`). Components register types through
    // `multi-custom-type` instead.
    s.push_str(MULTI_CUSTOM_TYPE_STUB);

    // ---- spatial-index: stub ----
    s.push_str(&format!(
        r##"impl spatial_index::Guest for Component {{
    fn name() -> String {{ "{primary}-stub-spatial".into() }}
    fn aliases() -> Vec<String> {{ Vec::new() }}
    fn capabilities() -> sitypes::IndexCapabilities {{
        sitypes::IndexCapabilities {{
            knn: false,
            within_distance: false,
            within_distance_wkb: false,
            update_after_build: false,
        }}
    }}
    fn build(_items: Vec<sitypes::BuildItem>) -> Result<u64, sitypes::SpatialError> {{
        Err(sitypes::SpatialError::UnsupportedOperation(
            "spatial-index not wired in scalar-first cut".into(),
        ))
    }}
    fn entry_count(_handle: u64) -> u64 {{ 0 }}
    fn query_envelope(_handle: u64, _env: sitypes::Envelope) -> Result<Vec<u64>, sitypes::SpatialError> {{
        Err(sitypes::SpatialError::UnsupportedOperation(
            "spatial-index not wired in scalar-first cut".into(),
        ))
    }}
    fn query_knn(_handle: u64, _query_bytes: Vec<u8>, _k: u32) -> Result<Vec<u64>, sitypes::SpatialError> {{
        Err(sitypes::SpatialError::UnsupportedOperation(
            "spatial-index not wired in scalar-first cut".into(),
        ))
    }}
    fn query_within_distance(_handle: u64, _query_env: sitypes::Envelope, _distance: f64) -> Result<Vec<u64>, sitypes::SpatialError> {{
        Err(sitypes::SpatialError::UnsupportedOperation(
            "spatial-index not wired in scalar-first cut".into(),
        ))
    }}
    fn query_within_distance_wkb(_handle: u64, _query_wkb: Vec<u8>, _distance: f64) -> Result<Vec<u64>, sitypes::SpatialError> {{
        Err(sitypes::SpatialError::UnsupportedOperation(
            "spatial-index not wired in scalar-first cut".into(),
        ))
    }}
    fn destroy(_handle: u64) {{}}
}}

"##,
        primary = primary,
    ));

    // ---- system-catalog: stub ----
    s.push_str(&format!(
        r##"impl system_catalog::Guest for Component {{
    fn catalog_name() -> String {{ "{primary}".into() }}
    fn list_tables() -> Result<Vec<sctypes::SystemTable>, sctypes::CatalogError> {{
        Ok(Vec::new())
    }}
    fn read_table(table_name: String) -> Result<
        Vec<Vec<sctypes::ScalarValue>>, sctypes::CatalogError,
    > {{
        Err(sctypes::CatalogError::UnknownTable(table_name))
    }}
    fn notify_extension_column_added(
        _session_id: u64,
        _catalog: String,
        _schema: String,
        _table_name: String,
        _column_name: String,
        _type_id: u32,
        _srid: Option<i32>,
        _coord_dim: Option<i32>,
    ) {{}}
    fn notify_extension_column_removed(
        _session_id: u64,
        _catalog: String,
        _schema: String,
        _table_name: String,
        _column_name: String,
    ) {{}}
    fn read_table_for_session(
        _session_id: u64,
        table_name: String,
    ) -> Result<Vec<Vec<sctypes::ScalarValue>>, sctypes::CatalogError> {{
        Err(sctypes::CatalogError::UnknownTable(table_name))
    }}
    fn notify_extension_column_raster_metadata(
        _session_id: u64,
        _catalog: String,
        _schema: String,
        _table_name: String,
        _column_name: String,
        _metadata: sctypes::RasterColumnMetadata,
    ) {{}}
}}

"##,
        primary = primary,
    ));

    // ---- index-plugin: stub ----
    s.push_str(&format!(
        r##"impl index::Guest for Component {{
    fn name() -> String {{ "{primary}-stub-index".into() }}
    fn type_id() -> u32 {{ 0 }}
    fn supported_types() -> Vec<ixtypes::LogicalType> {{ Vec::new() }}
    fn capabilities() -> ixtypes::IndexCapabilities {{
        ixtypes::IndexCapabilities {{
            point_lookup: false,
            range_scan: false,
            prefix_scan: false,
            ordering: false,
            spatial_search: false,
            fulltext_search: false,
            approximate_membership: false,
        }}
    }}
    fn create(_options: Vec<(String, String)>) -> Result<u64, ixtypes::IndexError> {{
        Err(unimpl_index_err())
    }}
    fn destroy(_handle: u64) {{}}
    fn insert(_handle: u64, _key: Vec<ixtypes::ScalarValue>, _row_id: u64) -> Result<(), ixtypes::IndexError> {{
        Err(unimpl_index_err())
    }}
    fn delete(_handle: u64, _key: Vec<ixtypes::ScalarValue>) -> Result<bool, ixtypes::IndexError> {{
        Err(unimpl_index_err())
    }}
    fn contains(_handle: u64, _key: Vec<ixtypes::ScalarValue>) -> Result<bool, ixtypes::IndexError> {{
        Err(unimpl_index_err())
    }}
    fn get(_handle: u64, _key: Vec<ixtypes::ScalarValue>) -> Result<Option<u64>, ixtypes::IndexError> {{
        Err(unimpl_index_err())
    }}
    fn begin_scan(
        _handle: u64,
        _start: ixtypes::ScanBound,
        _end: ixtypes::ScanBound,
        _direction: ixtypes::ScanDirection,
        _limit: Option<u64>,
    ) -> Result<u64, ixtypes::IndexError> {{
        Err(unimpl_index_err())
    }}
    fn next(_cursor: u64) -> Option<Result<ixtypes::IndexEntry, ixtypes::IndexError>> {{
        None
    }}
    fn close_scan(_cursor: u64) {{}}
    fn stats(_handle: u64) -> Result<ixtypes::IndexStats, ixtypes::IndexError> {{
        Err(unimpl_index_err())
    }}
    fn bulk_load(_handle: u64, _entries: Vec<ixtypes::IndexEntry>) -> Result<(), ixtypes::IndexError> {{
        Err(unimpl_index_err())
    }}
    fn serialize(_handle: u64) -> Result<Vec<u8>, ixtypes::IndexError> {{
        Err(unimpl_index_err())
    }}
    fn deserialize(_data: Vec<u8>) -> Result<u64, ixtypes::IndexError> {{
        Err(unimpl_index_err())
    }}
}}

fn unimpl_index_err() -> ixtypes::IndexError {{
    ixtypes::IndexError::Internal(
        "1D index not implemented in this {primary} bridge (scalar-first cut)".into(),
    )
}}

"##,
        primary = primary,
    ));

    // Export the Component as the world's entry point.
    s.push_str("bindings::export!(Component with_types_in bindings);\n");

    let _ = crate_name; // surface in README/CARGO; not used in lib.rs body
    Ok(s)
}

/// Build the scalar_function_registry Guest impl block. Walks the
/// post-classifier `scalar_entries` to materialize:
///   * per-name `list_functions()` metadata entries (with the
///     ParamShape-derived `param_types` widths the planner sees)
///   * per-name `return_type` dispatch arms (RetShape → LogicalType)
///   * per-name `execute` dispatch arms (the marshalling body)
fn build_scalar_registry_impl(
    scalar_entries: &[(interface_db::DispatchEntry, bool)],
    plan: &BridgePlan,
) -> String {
    // Collect determinism + propagates-null from the BridgePlan
    // side (the post-classifier DispatchEntry doesn't carry those).
    let mut det: std::collections::HashMap<String, (bool, bool)> =
        std::collections::HashMap::new();
    for ext in &plan.extensions {
        for sc in &ext.scalars {
            det.insert(
                sc.canonical_name.clone(),
                (sc.is_deterministic, sc.propagates_null),
            );
            for alias in &sc.aliases {
                det.insert(alias.clone(), (sc.is_deterministic, sc.propagates_null));
            }
        }
    }

    // First pass: build deduped sql_name list (mirrors the per-arm
    // walk pattern from duckdb-emit's build_scalar_arms — a SQL
    // name might surface multiple times if the entry classifier
    // produces an alias+canonical pair; first writer wins).
    let mut metas_block = String::new();
    let mut return_arms = String::new();
    let mut execute_arms = String::new();
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();

    for (entry, fallible) in scalar_entries {
        if !seen.insert(entry.sql_name.clone()) {
            continue;
        }
        let (deterministic, propagates_null) =
            det.get(&entry.sql_name).copied().unwrap_or((true, true));

        // ---- metadata entry ----
        let mut sig_block = String::new();
        sig_block.push_str("vec![");
        for p in &entry.shape.params {
            let lt = dispatch::paramshape_to_logicaltype(p);
            sig_block.push_str(&lt);
            sig_block.push_str(", ");
        }
        sig_block.push(']');
        let escaped = entry.sql_name.replace('"', "\\\"");
        metas_block.push_str(&format!(
            "        ftypes::ScalarFunctionMeta {{\n\
             \x20           name: \"{escaped}\".to_string(),\n\
             \x20           aliases: Vec::new(),\n\
             \x20           param_types: vec![{sig_block}],\n\
             \x20           is_deterministic: {deterministic},\n\
             \x20           propagates_null: {propagates_null},\n\
             \x20       }},\n",
            escaped = escaped,
            sig_block = sig_block,
            deterministic = deterministic,
            propagates_null = propagates_null,
        ));

        // ---- return_type arm ----
        let ret_logical = dispatch::retshape_to_logicaltype(&entry.shape.ret);
        return_arms.push_str(&format!(
            "            \"{escaped}\" => Ok({ret_logical}),\n",
        ));

        // ---- execute arm ----
        let body = dispatch::emit_scalar_arm_body(
            &entry.shape,
            *fallible,
            &entry.sql_name,
            "                ",
        );
        execute_arms.push_str(&format!(
            "            \"{escaped}\" => {{\n{body}\n            }}\n",
        ));
    }

    format!(
        r##"impl scalar_function_registry::Guest for Component {{
    fn list_functions() -> Vec<ftypes::ScalarFunctionMeta> {{
        vec![
{metas_block}        ]
    }}

    fn return_type(
        name: String,
        _input_types: Vec<ftypes::LogicalType>,
    ) -> Result<ftypes::LogicalType, ftypes::FunctionError> {{
        match name.as_str() {{
{return_arms}            other => Err(ftypes::FunctionError::UnknownFunction(other.into())),
        }}
    }}

    fn execute(
        name: String,
        args: Vec<ftypes::ScalarValue>,
    ) -> Result<ftypes::ScalarValue, ftypes::FunctionError> {{
        // Datafission's host can either short-circuit NULL inputs
        // engine-side or push them through to the guest. PostGIS
        // scalars uniformly propagate; for safety we short-circuit
        // here too so the marshalling helpers never see a Null arm.
        if args.iter().any(|v| matches!(v, ftypes::ScalarValue::Null)) {{
            return Ok(ftypes::ScalarValue::Null);
        }}
        match name.as_str() {{
{execute_arms}            other => Err(ftypes::FunctionError::UnknownFunction(other.into())),
        }}
    }}

    fn execute_batch(
        name: String,
        args_batch: Vec<Vec<ftypes::ScalarValue>>,
    ) -> Result<Vec<ftypes::ScalarValue>, ftypes::FunctionError> {{
        let mut out = Vec::with_capacity(args_batch.len());
        for row in args_batch {{
            out.push(<Self as scalar_function_registry::Guest>::execute(name.clone(), row)?);
        }}
        Ok(out)
    }}
}}

"##,
        metas_block = metas_block,
        return_arms = return_arms,
        execute_arms = execute_arms,
    )
}

const HEADER: &str =
    "// === GENERATED by sqlink-shim-codegen (target=datafission)  do not edit by hand ===\n\n";

/// ScalarValue ↔ Rust helpers ferried into the bridge's lib.rs
/// prelude. Mirror of the `arg_text` / `arg_blob` / `arg_f64` /
/// `arg_i64` set in sqlite-emit but unpacking from
/// `ftypes::ScalarValue` arms. Datafission's value variant is the
/// widest of the three (separate signed/unsigned int arms + date /
/// time / timestamp specialisations), all coerced into the same
/// common Rust primitive via the four helpers below.
const SCALARVALUE_HELPERS: &str = r##"// ─── ScalarValue arg helpers ───
//
// Mirror of sqlite-emit's `arg_text` / `arg_blob` / `arg_i64` set
// and duckdb-emit's `dv_*` set but unpacking from
// `ftypes::ScalarValue` arms. The datafission variant is the
// widest of the three (split signed/unsigned int arms + date /
// time / timestamp specialisations); helpers coerce to a common
// Rust primitive.

fn dfv_text<'a>(args: &'a [ftypes::ScalarValue], idx: usize, name: &str) -> Result<&'a str, ftypes::FunctionError> {
    match args.get(idx) {
        Some(ftypes::ScalarValue::Utf8(s)) => Ok(s.as_str()),
        _ => Err(ftypes::FunctionError::TypeError(format!(
            "{name}: arg {idx} must be UTF8"
        ))),
    }
}

fn dfv_blob<'a>(args: &'a [ftypes::ScalarValue], idx: usize, name: &str) -> Result<&'a [u8], ftypes::FunctionError> {
    match args.get(idx) {
        Some(ftypes::ScalarValue::Binary(b)) => Ok(b.as_slice()),
        Some(ftypes::ScalarValue::Utf8(s)) => Ok(s.as_bytes()),
        _ => Err(ftypes::FunctionError::TypeError(format!(
            "{name}: arg {idx} must be BINARY"
        ))),
    }
}

fn dfv_f64(args: &[ftypes::ScalarValue], idx: usize, name: &str) -> Result<f64, ftypes::FunctionError> {
    match args.get(idx) {
        Some(ftypes::ScalarValue::Float64(v)) => Ok(*v),
        Some(ftypes::ScalarValue::Float32(v)) => Ok(*v as f64),
        Some(ftypes::ScalarValue::Int64(v)) => Ok(*v as f64),
        Some(ftypes::ScalarValue::Int32(v)) => Ok(*v as f64),
        Some(ftypes::ScalarValue::Uint64(v)) => Ok(*v as f64),
        Some(ftypes::ScalarValue::Uint32(v)) => Ok(*v as f64),
        Some(ftypes::ScalarValue::Int16(v)) => Ok(*v as f64),
        Some(ftypes::ScalarValue::Int8(v)) => Ok(*v as f64),
        Some(ftypes::ScalarValue::Uint16(v)) => Ok(*v as f64),
        Some(ftypes::ScalarValue::Uint8(v)) => Ok(*v as f64),
        _ => Err(ftypes::FunctionError::TypeError(format!(
            "{name}: arg {idx} must be FLOAT"
        ))),
    }
}

fn dfv_i64(args: &[ftypes::ScalarValue], idx: usize, name: &str) -> Result<i64, ftypes::FunctionError> {
    match args.get(idx) {
        Some(ftypes::ScalarValue::Int64(v)) => Ok(*v),
        Some(ftypes::ScalarValue::Int32(v)) => Ok(*v as i64),
        Some(ftypes::ScalarValue::Uint64(v)) => Ok(*v as i64),
        Some(ftypes::ScalarValue::Uint32(v)) => Ok(*v as i64),
        Some(ftypes::ScalarValue::Int16(v)) => Ok(*v as i64),
        Some(ftypes::ScalarValue::Int8(v)) => Ok(*v as i64),
        Some(ftypes::ScalarValue::Uint16(v)) => Ok(*v as i64),
        Some(ftypes::ScalarValue::Uint8(v)) => Ok(*v as i64),
        Some(ftypes::ScalarValue::Boolean(b)) => Ok(if *b { 1 } else { 0 }),
        Some(ftypes::ScalarValue::Float64(v)) => Ok(*v as i64),
        Some(ftypes::ScalarValue::Float32(v)) => Ok(*v as i64),
        Some(ftypes::ScalarValue::Date(v)) => Ok(*v as i64),
        Some(ftypes::ScalarValue::Time(v)) => Ok(*v),
        Some(ftypes::ScalarValue::Timestamp(v)) => Ok(*v),
        _ => Err(ftypes::FunctionError::TypeError(format!(
            "{name}: arg {idx} must be INTEGER"
        ))),
    }
}

fn dfv_bool(args: &[ftypes::ScalarValue], idx: usize, name: &str) -> Result<bool, ftypes::FunctionError> {
    match args.get(idx) {
        Some(ftypes::ScalarValue::Boolean(b)) => Ok(*b),
        Some(ftypes::ScalarValue::Int64(v)) => Ok(*v != 0),
        Some(ftypes::ScalarValue::Int32(v)) => Ok(*v != 0),
        _ => Err(ftypes::FunctionError::TypeError(format!(
            "{name}: arg {idx} must be BOOLEAN"
        ))),
    }
}

/// Generic error formatter for fallible upstream WIT calls. The
/// dispatch arm wraps the upstream error via this fn into a
/// String the FunctionError::ExecutionError arm carries.
fn shim_err_string<E: core::fmt::Debug>(e: E) -> String {
    format!("{:?}", e)
}

"##;

/// Stub for aggregate_function_registry. Advertises nothing; every
/// per-call method returns `UnknownFunction`.
const AGGREGATE_STUB: &str = r##"impl aggregate_function_registry::Guest for Component {
    fn list_functions() -> Vec<ftypes::AggregateFunctionMeta> {
        Vec::new()
    }
    fn return_type(name: String, _input_types: Vec<ftypes::LogicalType>)
        -> Result<ftypes::LogicalType, ftypes::FunctionError>
    {
        Err(ftypes::FunctionError::UnknownFunction(name))
    }
    fn create_accumulator(name: String) -> Result<u64, ftypes::FunctionError> {
        Err(ftypes::FunctionError::UnknownFunction(name))
    }
    fn create_accumulator_with_config(name: String, _config: String) -> Result<u64, ftypes::FunctionError> {
        Err(ftypes::FunctionError::UnknownFunction(name))
    }
    fn create_accumulator_with_configs(name: String, _configs: Vec<String>) -> Result<u64, ftypes::FunctionError> {
        Err(ftypes::FunctionError::UnknownFunction(name))
    }
    fn accumulate(handle: u64, _value: ftypes::ScalarValue) -> Result<(), ftypes::FunctionError> {
        Err(ftypes::FunctionError::Internal(format!(
            "no accumulator at handle {handle} (aggregates not wired in scalar-first cut)"
        )))
    }
    fn accumulate_batch(handle: u64, _values: Vec<ftypes::ScalarValue>) -> Result<(), ftypes::FunctionError> {
        Err(ftypes::FunctionError::Internal(format!(
            "no accumulator at handle {handle} (aggregates not wired in scalar-first cut)"
        )))
    }
    fn merge(target: u64, _source: u64) -> Result<(), ftypes::FunctionError> {
        Err(ftypes::FunctionError::Internal(format!(
            "no accumulator at handle {target} (aggregates not wired in scalar-first cut)"
        )))
    }
    fn finalize(handle: u64) -> Result<ftypes::ScalarValue, ftypes::FunctionError> {
        Err(ftypes::FunctionError::Internal(format!(
            "no accumulator at handle {handle} (aggregates not wired in scalar-first cut)"
        )))
    }
    fn reset(_handle: u64) {}
    fn destroy_accumulator(_handle: u64) {}
}

"##;

const WINDOW_STUB: &str = r##"impl window_function_registry::Guest for Component {
    fn list_functions() -> Vec<ftypes::WindowFunctionMeta> {
        Vec::new()
    }
    fn return_type(name: String, _input_types: Vec<ftypes::LogicalType>)
        -> Result<ftypes::LogicalType, ftypes::FunctionError>
    {
        Err(ftypes::FunctionError::UnknownFunction(name))
    }
    fn compute_partition(
        name: String,
        _args_rows: Vec<Vec<ftypes::ScalarValue>>,
    ) -> Result<Vec<ftypes::ScalarValue>, ftypes::FunctionError> {
        Err(ftypes::FunctionError::UnknownFunction(name))
    }
}

"##;

const TABLE_STUB: &str = r##"impl table_function_registry::Guest for Component {
    fn list_functions() -> Vec<ftypes::TableFunctionMeta> {
        Vec::new()
    }
    fn output_schema(
        name: String,
        _input_types: Vec<ftypes::LogicalType>,
    ) -> Result<Vec<ftypes::ColumnInfo>, ftypes::FunctionError> {
        Err(ftypes::FunctionError::UnknownFunction(name))
    }
    fn begin(name: String, _args: Vec<ftypes::ScalarValue>) -> Result<u64, ftypes::FunctionError> {
        Err(ftypes::FunctionError::UnknownFunction(name))
    }
    fn next_row(_handle: u64) -> Option<Result<Vec<ftypes::ScalarValue>, ftypes::FunctionError>> {
        None
    }
    fn end(_handle: u64) {}
}

"##;

const MULTI_CUSTOM_TYPE_STUB: &str = r##"impl multi_custom_type::Guest for Component {
    fn list_types() -> Vec<multi_custom_type::CustomTypeMeta> {
        Vec::new()
    }
    fn serialize(_type_id: u32, value: Vec<u8>) -> Vec<u8> { value }
    fn deserialize(type_id: u32, _bytes: Vec<u8>) -> Result<Vec<u8>, ttypes::TypeError> {
        Err(ttypes::TypeError::Internal(format!(
            "no custom type at id {type_id} (multi-custom-type not wired in scalar-first cut)"
        )))
    }
    fn compare(_type_id: u32, _a: Vec<u8>, _b: Vec<u8>) -> ttypes::Ordering {
        ttypes::Ordering::Equal
    }
    fn hash_value(_type_id: u32, _value: Vec<u8>) -> u64 { 0 }
    fn display(type_id: u32, _value: Vec<u8>) -> String {
        format!("<type {type_id} (stub)>")
    }
    fn parse(type_id: u32, _input: String) -> Result<Vec<u8>, ttypes::TypeError> {
        Err(ttypes::TypeError::Internal(format!(
            "no custom type at id {type_id} (multi-custom-type not wired in scalar-first cut)"
        )))
    }
}

"##;

/// Discover which subdir of `wit_deps_root` holds the primary
/// shim's upstream WIT package. Same heuristic as sqlite-emit /
/// duckdb-emit's `pick_primary_shim_dir`.
fn pick_primary_shim_dir(
    primary: &str,
    wit_deps_root: &std::path::Path,
    shim_packages: &[datalink_shim_codegen_core::wit_parse::WitPackage],
) -> Option<std::path::PathBuf> {
    use datalink_shim_codegen_core::wit_parse;
    for pkg in shim_packages {
        let ns = pkg.ns_name.split(':').next().unwrap_or("");
        if ns == primary {
            if let Ok(rd) = std::fs::read_dir(wit_deps_root) {
                for e in rd.flatten() {
                    if !e.path().is_dir() {
                        continue;
                    }
                    if let Ok(Some(p)) = wit_parse::parse_package_dir(&e.path()) {
                        if p.ns_name == pkg.ns_name {
                            return Some(e.path());
                        }
                    }
                }
            }
        }
    }
    if let Ok(rd) = std::fs::read_dir(wit_deps_root) {
        for e in rd.flatten() {
            if !e.path().is_dir() {
                continue;
            }
            let name = e.file_name();
            let sname = name.to_string_lossy();
            if sname.starts_with(primary) {
                return Some(e.path());
            }
        }
    }
    if let Ok(rd) = std::fs::read_dir(wit_deps_root) {
        let mut paths: Vec<std::path::PathBuf> =
            rd.flatten().map(|e| e.path()).filter(|p| p.is_dir()).collect();
        paths.sort();
        for p in paths {
            let name = p.file_name().and_then(|s| s.to_str()).unwrap_or("");
            match name {
                "sqlite-extension" | "duckdb-extension" | "sfcgal-component"
                | "extension" | "function-plugin" | "sql-extension-plugin"
                | "type-plugin" | "spatial-index-plugin"
                | "system-catalog-plugin" | "index-plugin" => continue,
                _ => return Some(p),
            }
        }
    }
    None
}

fn split_pkg(pkg: &str) -> (String, String) {
    match pkg.find(':') {
        Some(i) => (pkg[..i].to_string(), pkg[i + 1..].to_string()),
        None => (pkg.to_string(), String::new()),
    }
}

fn sanitize_module(s: &str) -> String {
    s.replace('-', "_")
}
