//! Emit the `README.md` for the wasm-component bridge crate
//! (datafission target).

use shim_bridge_codegen_core::BridgePlan;

pub fn readme(plan: &BridgePlan, crate_name: &str) -> String {
    let primary = plan
        .extensions
        .first()
        .map(|e| e.name.as_str())
        .unwrap_or("shim");
    let version = plan
        .extensions
        .first()
        .map(|e| e.version.as_str())
        .unwrap_or("0.1.0");

    let (sc, ag, tf, wf, ct, op, cw, pp, sct, idx) = match plan.extensions.first() {
        Some(e) => (
            e.scalars.len(),
            e.aggregates.len(),
            e.table_functions.len(),
            e.window_functions.len(),
            e.column_types.len(),
            e.operators.len(),
            e.cast_rewrites.len(),
            e.preprocessor_patterns.len(),
            e.system_catalog_tables.len(),
            e.spatial_indexes.len(),
        ),
        None => (0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
    };

    let crate_underscore = crate_name.replace('-', "_");

    format!(
        r##"# {crate_name}

Generated by [`sqlink-shim-codegen`](https://github.com/tegmentum/sqlink-shim-codegen)
from `{primary}-interface.sqlite` with `--target datafission`.

**Do not edit by hand** — regenerate from the interface DB.

## Status

This bridge is a **scalar-first cut**. Scalars are wired
end-to-end against the `datafission:extension@1.0.0` composite
world; aggregates / window / table function registries advertise
empty `list-functions` and reject per-name dispatches with
`FunctionError::UnknownFunction`. Custom-type, spatial-index,
system-catalog, and index-plugin interfaces export stubs that
return empty advertisements or `Internal` errors. The
verification gate at this step is that the crate
`cargo build --target wasm32-wasip2 --release` cleanly — full
smoke-tests against a df-plugin-loader runtime are deferred to
follow-up work.

## Surface from the interface DB

| extension | version | scalars | aggregates | UDTFs | windows | types | operators | casts | preprocessors | catalog | indexes |
|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|
| {primary} | {version} | {sc} | {ag} | {tf} | {wf} | {ct} | {op} | {cw} | {pp} | {sct} | {idx} |

## Build

```sh
cargo build --target wasm32-wasip2 --release
```

The build needs `wit-bindgen` and an installed `wasm32-wasip2`
target (`rustup target add wasm32-wasip2`).

## Compose with the upstream shim wasm

The datafission target composes the same way the SQLite and
DuckDB targets do — `wac plug` the upstream
`<primary>-composed.wasm` into this crate's wasm:

```sh
wac plug \
  --plug ~/git/{primary}-wasm/{primary}-composed.wasm \
  -o {primary}-datafission-loadable.wasm \
  target/wasm32-wasip2/release/{crate_underscore}.wasm
```

The composed artifact loads into df-plugin-loader via
`CREATE EXTENSION <name> FROM '<path>'`.

## Regenerate

```sh
cd ~/git/sqlink-shim-codegen
cargo run --release -- \
  --target datafission \
  --interface /path/to/{primary}-interface.sqlite \
  --out ~/git/{crate_name}
```

## License

Apache-2.0.
"##,
        crate_name = crate_name,
        primary = primary,
        version = version,
        crate_underscore = crate_underscore,
        sc = sc,
        ag = ag,
        tf = tf,
        wf = wf,
        ct = ct,
        op = op,
        cw = cw,
        pp = pp,
        sct = sct,
        idx = idx,
    )
}
