//! Emit `Cargo.toml` for the wasm-component bridge crate
//! (datafission target).
//!
//! The shape mirrors `~/git/datafission/extensions/postgis/Cargo.toml`
//! (the implementation oracle for hand-written datafission
//! extensions): `crate-type = ["cdylib"]` for `wasm32-wasip2`, a
//! `wit-bindgen` dep, plus serde / serde_json for the JSON-as-TEXT
//! list helpers the SQLite + DuckDB-target bridges ship.
//!
//! No `wasmtime` / `rusqlite` — pure wasm component code; the
//! df-plugin-loader supplies the imports at runtime.

use shim_bridge_codegen_core::BridgePlan;

pub fn cargo_toml(plan: &BridgePlan, crate_name: &str) -> String {
    let primary = plan
        .extensions
        .first()
        .map(|e| e.name.as_str())
        .unwrap_or("shim");
    format!(
        r##"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"
description = """
Generated by sqlink-shim-codegen (--target datafission).
Bridges the {primary} DataFission shim onto the canonical
`datafission:extension@1.0.0` composite world as a wasm component.
Imports {primary}:wasm/*; exports the eleven datafission capability
interfaces (identity + sql-extension/metadata + scalar/aggregate/
window/table function registries + custom-type + multi-custom-type
+ spatial-index + system-catalog + index). Scalar-first cut:
scalars are wired; the other registries advertise empty list-functions
or return FunctionError::UnknownFunction at call time.
"""
license = "Apache-2.0"
publish = false

# Standalone package — NOT part of any workspace. Building this
# crate requires the wasm32-wasip2 target and a wit-bindgen-
# compatible toolchain; consumer workspaces shouldn't try to
# compile it as part of `cargo build`.
[workspace]
members = ["."]

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = {{ version = "0.41", features = ["macros"] }}
wit-bindgen-rt = {{ version = "0.41", features = ["bitflags"] }}
# Scalar-first cut: serde + serde_json are present for parity
# with sqlite-emit's JSON-as-TEXT helpers (`list<f64>` args parsed
# from `'[1.0, 2.0]'` TEXT). The datafission-target dispatch arms
# in this cut don't currently exercise them, but the build needs
# them on the dependency manifest for any future serde_json
# references in the generated prelude to resolve.
serde = {{ version = "1", default-features = false, features = ["derive", "alloc"] }}
serde_json = {{ version = "1", default-features = false, features = ["alloc"] }}

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
panic = "abort"
"##,
        crate_name = crate_name,
        primary = primary,
    )
}
