//! Neutral core for the `ggsql` PARSER extension — the `VISUALIZE`
//! statement parse/rewrite logic — written ONCE and consumed by BOTH the
//! ducklink (`duckdb:extension`) and sqlink (`sqlite:extension`) shims.
//!
//! # Two consumers, one engine
//!
//! The rewrite engine is [`parse::parse_visualize`] returning a neutral
//! [`Outcome`](parse::Outcome) (text in, SQL text out). The two DB
//! surfaces differ in how a host offers a failed statement to an
//! extension, so each shim adapts the same [`Outcome`]:
//!
//!   * **ducklink** has a first-class `ParserExtension` hook
//!     (`parser-dispatch.call-parse`): a thin hand-written shim maps
//!     [`Outcome`] onto `parse-outcome` (`declined` / `rewrite`) and
//!     `duckerror` for `Invalid`.
//!   * **sqlink** — SQLite's amalgamation parser is NOT extensible, so
//!     there is no in-engine hook. The cleanest viable equivalent is a
//!     host-shell parse-failure INTERCEPT: on a built-in parse error the
//!     host offers the statement to a declared parser entrypoint. That
//!     entrypoint is the reserved scalar [`PARSE_FN`] declared below, so
//!     the sqlink shim is GENERATED by `datalink_extcore::sqlite_shim!`
//!     exactly like every other scalar in the catalog — no bespoke
//!     parser glue. `Declined` -> NULL (host treats NULL/empty as
//!     "decline"), `Rewrite(sql)` -> the SQL text, `Invalid` -> `Err`.
//!
//! # Codegen status (honest)
//!
//! The sqlink parser shim is fully write-once-generated today (it rides
//! the scalar `declare!` + `sqlite_shim!` path via [`PARSE_FN`]). The
//! ducklink parser-dispatch shim is a ~10-line hand-written adapter over
//! [`parse::parse_visualize`]; a `parser!` `declare!` arm that also emits
//! the ducklink parser-dispatch shim is the documented follow-on.

#![no_std]

extern crate alloc;

use datalink_extcore::NeutralValue;

pub mod parse;

pub use parse::{parse_visualize, Outcome};

/// The reserved scalar name the sqlink host-shell parse-failure intercept
/// looks for. Any loaded extension that declares a scalar with this name
/// IS a parser extension; the host calls it with the failed statement
/// text and runs a non-NULL/non-empty return as a SQL rewrite. Mirrors
/// (in spirit) ducklink's `parser.register-parser-extension`, but realized
/// over the existing scalar surface since SQLite has no parser hook.
pub const PARSE_FN: &str = "__sqlink_parse";

datalink_extcore::declare! {
    core = Core;
    extension = "ggsql";
    version = env!("CARGO_PKG_VERSION");

    // The sqlink parser entrypoint. Generated into a `sqlite:extension`
    // scalar by `sqlite_shim!`. The host-shell intercept calls this on a
    // built-in parse failure; the body is the shared neutral rewrite
    // engine. NULL return == declined; an Err == a clean parse error.
    scalar __sqlink_parse(text) -> text [propagate, deterministic] = |args| {
        let q = args.arg_text(0, PARSE_FN)?;
        match parse::parse_visualize(&q) {
            parse::Outcome::Declined => Ok(NeutralValue::Null),
            parse::Outcome::Invalid(msg) => Err(msg),
            parse::Outcome::Rewrite(sql) => Ok(NeutralValue::Text(sql)),
        }
    };
}

#[cfg(test)]
mod tests {
    extern crate std;
    use super::*;
    use alloc::string::String;
    use datalink_extcore::ExtCore;

    fn t(s: &str) -> NeutralValue {
        NeutralValue::Text(String::from(s))
    }
    fn idx(n: &str) -> usize {
        Core::DECLS.iter().position(|d| d.name == n).unwrap()
    }

    #[test]
    fn parse_fn_is_declared() {
        assert_eq!(Core::DECLS.len(), 1);
        assert_eq!(Core::DECLS[0].name, PARSE_FN);
    }

    #[test]
    fn scalar_declined_is_null() {
        let r = Core::dispatch(idx(PARSE_FN), &[t("SELECT 1")]).unwrap();
        assert_eq!(r, NeutralValue::Null);
    }

    #[test]
    fn scalar_rewrite_carries_sql() {
        let r = Core::dispatch(idx(PARSE_FN), &[t("VISUALIZE SELECT a, b FROM t")]).unwrap();
        match r {
            NeutralValue::Text(sql) => {
                assert!(sql.contains("__viz"));
                assert!(sql.to_ascii_uppercase().contains("ORDER BY"));
            }
            other => panic!("expected rewrite text, got {other:?}"),
        }
    }

    #[test]
    fn scalar_invalid_is_err() {
        let r = Core::dispatch(idx(PARSE_FN), &[t("VISUALIZE")]);
        assert!(r.is_err());
    }
}
