//! Neutral core for the `dplyr` PARSER extension — a dplyr-pipeline ->
//! SQL transpiler — written ONCE and consumed by BOTH the ducklink
//! (`duckdb:extension`) and sqlink (`sqlite:extension`) shims. Mirrors
//! the ggsql-core split exactly.
//!
//! # Two consumers, one engine
//!
//! The transpiler is [`parse::parse_dplyr`] returning a neutral
//! [`Outcome`](parse::Outcome) (text in, SQL text out). The two DB
//! surfaces differ only in how a host offers a failed statement to an
//! extension, so each shim adapts the same [`Outcome`]:
//!
//!   * **ducklink** has a first-class `ParserExtension` hook
//!     (`parser-dispatch.call-parse`): a thin hand-written shim maps
//!     [`Outcome`] onto `parse-outcome` (`declined` / `rewrite`) and
//!     `duckerror` for `Invalid`.
//!   * **sqlink** — SQLite's amalgamation parser is NOT extensible, so
//!     the host-shell parse-failure INTERCEPT offers the statement to the
//!     reserved scalar [`PARSE_FN`] declared below; the sqlink shim is
//!     GENERATED by `datalink_extcore::sqlite_shim!` exactly like every
//!     other scalar in the catalog — no bespoke parser glue.
//!
//! # Codegen status (honest)
//!
//! The sqlink parser shim is fully write-once-generated today (it rides
//! the scalar `declare!` + `sqlite_shim!` path via [`PARSE_FN`]). The
//! ducklink parser-dispatch shim is a ~10-line hand-written adapter over
//! [`parse::parse_dplyr`] — the same status ggsql-core documents.

#![no_std]

extern crate alloc;

use datalink_extcore::NeutralValue;

pub mod parse;

pub use parse::{parse_dplyr, Dialect, Outcome, DUCKDB, SQLITE};

/// The reserved scalar name the sqlink host-shell parse-failure intercept
/// looks for (shared convention with every parser extension; see
/// ggsql-core's `PARSE_FN`).
pub const PARSE_FN: &str = "__sqlink_parse";

datalink_extcore::declare! {
    core = Core;
    extension = "dplyr";
    version = env!("CARGO_PKG_VERSION");

    // The sqlink parser entrypoint. Generated into a `sqlite:extension`
    // scalar by `sqlite_shim!`. The host-shell intercept calls this on a
    // built-in parse failure; the body is the shared neutral transpiler.
    // NULL return == declined; an Err == a clean parse error.
    scalar __sqlink_parse(text) -> text [propagate, deterministic] = |args| {
        let q = args.arg_text(0, PARSE_FN)?;
        // The sqlite host-shell intercept always runs against SQLite, so
        // the entrypoint emits the SQLite dialect of the rewrite.
        match parse::parse_dplyr(&q, &parse::SQLITE) {
            parse::Outcome::Declined => Ok(NeutralValue::Null),
            parse::Outcome::Invalid(msg) => Err(msg),
            parse::Outcome::Rewrite(sql) => Ok(NeutralValue::Text(sql)),
        }
    };
}

#[cfg(test)]
mod tests {
    extern crate std;
    use super::*;
    use alloc::string::String;
    use datalink_extcore::ExtCore;

    fn t(s: &str) -> NeutralValue {
        NeutralValue::Text(String::from(s))
    }
    fn idx(n: &str) -> usize {
        Core::DECLS.iter().position(|d| d.name == n).unwrap()
    }

    #[test]
    fn parse_fn_is_declared() {
        assert_eq!(Core::DECLS.len(), 1);
        assert_eq!(Core::DECLS[0].name, PARSE_FN);
    }

    #[test]
    fn scalar_declined_is_null() {
        let r = Core::dispatch(idx(PARSE_FN), &[t("SELECT 1")]).unwrap();
        assert_eq!(r, NeutralValue::Null);
    }

    #[test]
    fn scalar_rewrite_carries_sql() {
        let r = Core::dispatch(
            idx(PARSE_FN),
            &[t("dplyr( t |> filter(a == 1) |> select(a) )")],
        )
        .unwrap();
        match r {
            NeutralValue::Text(sql) => {
                assert!(sql.contains("SELECT a FROM t"));
                assert!(sql.contains("WHERE (a = 1)"));
            }
            other => panic!("expected rewrite text, got {other:?}"),
        }
    }

    #[test]
    fn scalar_invalid_is_err() {
        let r = Core::dispatch(idx(PARSE_FN), &[t("dplyr()")]);
        assert!(r.is_err());
    }
}
